### ISSUE TITLE
TOCs of a couple of discs that cause whipper to fail

### ISSUE THREAD

**Issue by BonkaBonka** [whipper-team/whipper#183]
I've created a gist, https://gist.github.com/BonkaBonka/884166f337f7d31d9146df0b909031e2, with the TOC files from two discs I have that cause whipper to fail as mentioned in #174.

**Comment by ubitux** [comment]
I have one more with the following:

```
// Track 7
TRACK AUDIO
COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "000000000000"
key: ISRC
key: 000000000000
CD_TEXT {
  LANGUAGE 0 {
    TITLE "\316\011\366\"
```

...leading to:

```
Traceback (most recent call last):
  File "/home/ux/.local/bin/whipper", line 11, in <module>
    load_entry_point('whipper', 'console_scripts', 'whipper')()
  File "/home/ux/src/whipper/whipper/command/main.py", line 32, in main
    ret = cmd.do()
  File "/home/ux/src/whipper/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/home/ux/src/whipper/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/home/ux/src/whipper/whipper/command/cd.py", line 181, in do
    self.device, offset)
  File "/home/ux/src/whipper/whipper/common/program.py", line 138, in getTable
    t = cdrdao.ReadTableTask(device)
  File "/home/ux/src/whipper/whipper/program/cdrdao.py", line 93, in ReadTableTask
    return read_toc(device)
  File "/home/ux/src/whipper/whipper/program/cdrdao.py", line 45, in read_toc
    toc.parse()
  File "/home/ux/src/whipper/whipper/image/toc.py", line 210, in parse
    value = value.decode('string-escape').decode('latin-1')
ValueError: Trailing \ in string
```

It's actually full of stuff like this, more or less supported:

```
// Track 1
TRACK AUDIO
COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "000000000000"
key: ISRC
key: 000000000000
CD_TEXT {
  LANGUAGE 0 {
    TITLE "\303\305"
    PERFORMER "\321!"
  }
}
FILE "data.wav" 0 04:33:53


// Track 2
TRACK AUDIO
COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "000000000000"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "\017\350e\227c/\366\031"
    PERFORMER "\321!"
  }
}
FILE "data.wav" 04:33:53 03:22:30
START 00:02:00
```

**Comment by JoeLametta** [comment]
Related to #169.
