### ISSUE TITLE
whipper offset find exception

### ISSUE THREAD

**Issue by tlc** [whipper-team/whipper#208]
> $ whipper offset find -o 667
Checking device /dev/sr0
ERROR:whipper.common.accurip:error retrieving AccurateRip entry: 404 Not Found <Response [404]>
WARNING:whipper.common.accurip:entry not found in AccurateRip database
Accuraterip entry not found
Trying read offset 667 ...
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 9, in <module>
    load_entry_point('whipper==0.5.1', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.5.1-py2.7.egg/whipper/command/main.py", line 32, in main
    ret = cmd.do()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.5.1-py2.7.egg/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.5.1-py2.7.egg/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.5.1-py2.7.egg/whipper/command/offset.py", line 142, in do
    c, i = match(archecksums, 1, responses)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.5.1-py2.7.egg/whipper/command/offset.py", line 111, in match
    for i, r in enumerate(responses):
TypeError: 'NoneType' object is not iterable

**Comment by JoeLametta** [comment]
It seems that whipper checks if there are AccurateRip's responses but only warns if there are none. Instead of just warning, in case there are no responses, it should inform the user and quit.

**Comment by JoeLametta** [comment]
I think this issue has been solved in whipper `v0.6.0`.

**Comment by twvandewarker** [comment]
I am having this same issue in version 0.7.2. I have a debug log here, should I start a new issue? Thanks!

```
$ WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper offset find
Checking device /dev/sr0
Accuraterip entry not found
Trying read offset 6 ...
Traceback (most recent call last):      
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.2', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/whipper/command/main.py", line 36, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper/command/offset.py", line 140, in do
    c, i = match(archecksums, 1, responses)
  File "/usr/lib/python2.7/site-packages/whipper/command/offset.py", line 109, in match
    for i, r in enumerate(responses):
TypeError: 'NoneType' object is not iterable
```

[whipper.log.gz](https://github.com/whipper-team/whipper/files/2555381/whipper.log.gz)

**Comment by JoeLametta** [comment]
> I am having this same issue in version 0.7.2. I have a debug log here, should I start a new issue? Thanks!

Reopened, thanks for the issue report!

**Comment by JoeLametta** [comment]
Confirmed: whipper should abort the offset find operation if no remote AccurateRip entries are found...
Fix coming soon. :wink: 

https://github.com/whipper-team/whipper/blob/30785b8d1b95611c808e0e2d1c035f6511a5b39f/whipper/command/offset.py#L95-L96

**Comment by varac** [comment]
Happening also with a self-built docker image following the README.md from latetst master of today:

```
 …/audio/cd-ripping/whipper | whipper offset find -o 6
Checking device /dev/cdrom
eject: CD-ROM tray close command failed: Input/output error
ERROR:whipper.common.accurip:error retrieving AccurateRip entry: 404 Not Found <Response [404]>
WARNING:whipper.common.accurip:entry not found in AccurateRip database
Accuraterip entry not found
Trying read offset 6 ...
Traceback (most recent call last):      
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.2', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.2-py2.7.egg/whipper/command/main.py", line 36, in main
    ret = cmd.do()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.2-py2.7.egg/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.2-py2.7.egg/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.2-py2.7.egg/whipper/command/offset.py", line 140, in do
    c, i = match(archecksums, 1, responses)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.2-py2.7.egg/whipper/command/offset.py", line 109, in match
    for i, r in enumerate(responses):
TypeError: 'NoneType' object is not iterable
```

**Comment by JoeLametta** [comment]
> Happening also with a self-built docker image following the README.md from latetst master of today:
> Isn't this image built on every new commit ? If not, please push a new build.

That image is built from the master branch, which I've decided starting with release v0.7.2 is going to be updated only when new tagged releases are ready to be published.
Pull requests are developed into feature/bugfix branches: if accepted those are merged into the development branch.
Just issue the following command:

```
docker pull joelametta/whipper:develop
```

:wink:
