### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'offset'

### ISSUE THREAD

**Issue by spvkgn** [whipper-team/whipper#230]
```
$ whipper cd info
Checking device /dev/sr0
CDDB disc id: 630e1d08
MusicBrainz disc id ibP6iFiB14iye.JALRZ9kCdLmD8-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+8+271159+150+46261+79254+109237+125375+145820+202649+242631&tracks=8&id=ibP6iFiB14iye.JALRZ9kCdLmD8-
Disc duration: 01:00:13.453, 8 audio tracks

Matching releases:

Artist  : The Pax Cecilia
Title   : Blessed Are the Bonds
Duration: 01:00:13.451
URL     : https://musicbrainz.org/release/428a9519-b114-4cc1-8080-9fb71997ad11
Release : 428a9519-b114-4cc1-8080-9fb71997ad11
Type    : Album

Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.6.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/dist-packages/whipper/command/main.py", line 40, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/dist-packages/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/dist-packages/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/dist-packages/whipper/command/cd.py", line 150, in do
    self.device, self.options.offset)
AttributeError: 'Namespace' object has no attribute 'offset'
```
[whipper.log.gz](https://github.com/JoeLametta/whipper/files/1710815/whipper.log.gz)

**Comment by Matt07211** [comment]
Reproduced on Solus, with whipper 0.6.0 and Python 2.7.14

```
$ WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper cd info
Checking device /dev/sr0
CDDB disc id: 2a0ff914
MusicBrainz disc id NEZ.yGBoGJCYkr1uZ.r.GUK4P4E-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+20+306886+150+20851+41245+55417+65922+80277+91841+104052+116410+126941+136619+147824+160011+173949+185412+201484+251471+263470+275677+288839&tracks=20&id=NEZ.yGBoGJCYkr1uZ.r.GUK4P4E-
Disc duration: 01:08:09.813, 20 audio tracks

Matching releases:

Artist  : Creedence Clearwater Revival
Title   : Chronicle: The 20 Greatest Hits
Duration: 01:08:10.585
URL     : https://musicbrainz.org/release/72d361db-4ee2-484f-812c-0c60830336f6
Release : 72d361db-4ee2-484f-812c-0c60830336f6
Type    : Compilation
Barcode : 025218000222
Cat no  : 0025218000222

Artist  : Creedence Clearwater Revival
Title   : Chronicle
Duration: 01:08:10.585
URL     : https://musicbrainz.org/release/cc09c4a7-2f17-3c5d-abdd-cea3fe362045
Release : cc09c4a7-2f17-3c5d-abdd-cea3fe362045
Type    : Compilation
Barcode : 025218000222
Cat no  : FCD CCR2-2

Artist  : Creedence Clearwater Revival
Title   : Chronicle
Duration: 01:08:09.918
URL     : https://musicbrainz.org/release/f9a8e98f-b58f-4039-b2a2-18cd835a65eb
Release : f9a8e98f-b58f-4039-b2a2-18cd835a65eb
Type    : Compilation
Barcode : 025218000222
Cat no  : FCD-623-CCR2

Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.6.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/whipper-0.6.0-py2.7.egg/whipper/command/main.py", line 40, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper-0.6.0-py2.7.egg/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper-0.6.0-py2.7.egg/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper-0.6.0-py2.7.egg/whipper/command/cd.py", line 150, in do
    self.device, self.options.offset)
AttributeError: 'Namespace' object has no attribute 'offset'
```
[whipper.log](https://github.com/JoeLametta/whipper/files/1709982/whipper.log)

**Comment by JoeLametta** [comment]
Interesting comment by @RecursiveForest ([link](https://github.com/JoeLametta/whipper/pull/235#issuecomment-369338215)):

> A brief inquiry yields that offset is not otherwised used by info except by program.getTable(), which caches the offset along with the disc "Table" (an internal data structure roughly resembling the table of contents). If the offset stored in the cache is used by anything remains to be verified.
> 
> Interestingly, this bug harkens back to morituri days, where thomasvs left a note "# Hackish fix for a broken commit", where he also set the offset to 0 by default for ... cd info and ... cd rip after introducing the ... cd info command.

**Comment by NoSuck** [comment]
I can reproduce the issue running 0.7.0 on [the number-one distro for script kiddies](https://www.archlinux.org/).  I explicitly passed the drive offset in order to work around the issue mentioned by @thwaller but ran into *another* error:

```
whipper -e never cd rip --offset 667
```

```
creating output directory ········································
found Hidden Track One Audio from frame 0 to 149
Ripping track 0 of 13: ······················································
CRCs match for track 0
Peak level: 0
Rip quality: 100.00%
HTOA discarded, contains digital silence
Ripping track 1 of 13: ···················································
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 30000000
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 1 of 13 (try 2): ···················································
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 30000000
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 1 of 13 (try 3): ···················································
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 30000000
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 1 of 13 (try 4): ···················································
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 30000000
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 1 of 13 (try 5): ···················································
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 30000000
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
CRITICAL:whipper.command.cd:Giving up on track 1 after 5 times
track can't be ripped. Rip attempts number is equal to 'MAX_TRIES'
```

The album is obscure enough to be considered identifying information and has thus been redacted.  If a developer requires a full error log, please let me know, and I will provide it privately.

**Comment by JoeLametta** [comment]
> but ran into _another_ error:

The discussion about this bug is in #234.
