### ISSUE TITLE
Disc template KeyError

### ISSUE THREAD

**Issue by spvkgn** [whipper-team/whipper#279]
```
$ WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper cd rip
Using configured read offset 48
Checking device /dev/sr0
Reading TOC...
CDDB disc id: 630e1d08
MusicBrainz disc id ibP6iFiB14iye.JALRZ9kCdLmD8-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+8+271159+150+46261+79254+109237+125375+145820+202649+242631&tracks=8&id=ibP6iFiB14iye.JALRZ9kCdLmD8-
Disc duration: 01:00:13.453, 8 audio tracks

Matching releases:

Artist  : The Pax Cecilia
Title   : Blessed Are the Bonds
Duration: 01:00:13.451
URL     : https://musicbrainz.org/release/428a9519-b114-4cc1-8080-9fb71997ad11
Release : 428a9519-b114-4cc1-8080-9fb71997ad11
Type    : Album

Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/dist-packages/whipper/command/main.py", line 36, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/dist-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/dist-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/dist-packages/whipper/command/cd.py", line 181, in do
    self.doCommand()
  File "/usr/lib/python2.7/dist-packages/whipper/command/cd.py", line 320, in doCommand
    self.program.metadata)
  File "/usr/lib/python2.7/dist-packages/whipper/common/program.py", line 240, in getPath
    return os.path.join(outdir, template % v)
KeyError: u't'
```
```
$ cat ~/.config/whipper/whipper.conf 
[drive:PIONEER%20%3ADVD-RW%20%20DVR-109%20%3A1.58]
vendor = PIONEER
model = DVD-RW  DVR-109
release = 1.58
defeats_cache = True
read_offset = 48

[whipper.cd.rip]
unknown = True
output_directory = ~/Music
track_template = %%A - %%d (%%y)/%%t. %%n
disc_template = %(track_template)s
```
When I delete `[whipper.cd.rip]` section, this error not occurs.

[whipper.log.gz](https://github.com/JoeLametta/whipper/files/2169137/whipper.log.gz)

**Comment by RecursiveForest** [comment]
If you single quote your `track_template` line, does the crash still occur?

If you could include a debug log in your report that would be helpful: https://github.com/JoeLametta/whipper#bug-reports--feature-requests

Thanks for bringing this to our attention. :)

**Comment by spvkgn** [comment]
@RecursiveForest Single quoting does not help, it crashes with same error.
Thanks for your answer, please see log file attached in first comment.

**Comment by RecursiveForest** [comment]
Oops >_< re: whipper.log

Okay, the bug is partially in our documentation. If you edit the `disc_template` line to something like `disc_template = %%A - %%d (%%y)` you should not experience a crash.

The "%t" format type is only applicable to the track_template-- attempting to use it in the disc template is causing a crash. Our code should handle this gracefully instead of crashing.

Our documentation should say something like:
```yaml
disc_template = %%A - %%d (%%y)
track_template = %(disc_template)s/%%t. %%n```
