### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-18: ordinal not in range(128)

### ISSUE THREAD

**Issue by shibumi** [whipper-team/whipper#315]
Hi, I get the following error with the newest whipper release 0.7.1

```
Using configured read offset 103
Checking device /dev/sr0
Reading TOC...
CDDB disc id: 3a057906
MusicBrainz disc id 9qf9_pRRoi4L5pkQirWY2pMcwWs-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+6+105238+150+16152+35617+56552+75518+91948&tracks=6&id=9qf9_pRRoi4L5pkQirWY2pMcwWs-
Disc duration: 00:23:21.173, 6 audio tracks

Matching releases:

Artist  : GLIM SPANKY
Title   : 焦燥
Duration: 00:23:14.000
URL     : https://musicbrainz.org/release/2624bc86-f287-436c-91a8-6f24ea6e0901
Release : 2624bc86-f287-436c-91a8-6f24ea6e0901
Type    : EP
Barcode : 4988005824998
Cat no  : TYCT-60038

output directory ./ep/GLIM SPANKY - 焦燥 already exists
Verifying track 1 of 6: 01. GLIM SPANKY - 焦燥.flac
I am doing something.   0 %
flac 1.3.2
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

01. GLIM SPANKY - 焦燥.flac: done         
Verifying track 2 of 6: 02. GLIM SPANKY - MIDNIGHT CIRCUS.flac
I am doing something.   0 %
flac 1.3.2
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

02. GLIM SPANKY - MIDNIGHT CIRCUS.flac: done         
Verifying track 3 of 6: 03. GLIM SPANKY - ダミーロックとブルース (Live).flac
I am doing something.   0 %
flac 1.3.2
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

03. GLIM SPANKY - ダミーロックとブルース (Live).flac: done         
Verifying track 4 of 6: 04. GLIM SPANKY - Flower Song (Live).flac
I am doing something.   0 %
flac 1.3.2
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

04. GLIM SPANKY - Flower Song (Live).flac: done         
Verifying track 5 of 6: 05. GLIM SPANKY - Rolling In The Deep.flac
I am doing something.   0 %
flac 1.3.2
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

05. GLIM SPANKY - Rolling In The Deep.flac: done         
Verifying track 6 of 6: 06. GLIM SPANKY - ひこうき雲.flac
I am doing something.   0 %
flac 1.3.2
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

06. GLIM SPANKY - ひこうき雲.flac: done         
Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.1', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/whipper/command/main.py", line 36, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper/command/cd.py", line 181, in do
    self.doCommand()
  File "/usr/lib/python2.7/site-packages/whipper/command/cd.py", line 474, in doCommand
    self.program.writeCue(discName)
  File "/usr/lib/python2.7/site-packages/whipper/common/program.py", line 599, in writeCue
    cuePath = common.truncate_filename(discName + '.cue')
  File "/usr/lib/python2.7/site-packages/whipper/common/common.py", line 164, in truncate_filename
    fn_lim = os.pathconf(p, 'PC_NAME_MAX')  # max.filename length in bytes
UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-18: ordinal not in range(128)
```

**Comment by JoeLametta** [comment]
Thanks for the issue report!
Hm, that's strange... could you try ripping it again and attach a debug logfile? (in the meantime I'll try to replicate the issue on my own).

**Comment by JoeLametta** [comment]
Debug logfiles can be generated as explained in the [bug reports & feature requests](https://github.com/whipper-team/whipper#bug-reports--feature-requests) section of whipper's [README](https://github.com/whipper-team/whipper/blob/master/README.md).

**Comment by Freso** [comment]
I just got a similar traceback too:
```python-traceback
Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.1', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/whipper/command/main.py", line 36, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper/command/cd.py", line 181, in do
    self.doCommand()
  File "/usr/lib/python2.7/site-packages/whipper/command/cd.py", line 474, in doCommand
    self.program.writeCue(discName)
  File "/usr/lib/python2.7/site-packages/whipper/common/program.py", line 599, in writeCue
    cuePath = common.truncate_filename(discName + '.cue')
  File "/usr/lib/python2.7/site-packages/whipper/common/common.py", line 164, in truncate_filename
    fn_lim = os.pathconf(p, 'PC_NAME_MAX')  # max.filename length in bytes
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 26: ordinal not in range(128)
```

Let me try and reproduce with debug log turned on…

**Comment by Freso** [comment]
So it's the `common.truncate_filename()` method introduced with https://github.com/whipper-team/whipper/commit/02fd9620948597d2a8d32683b1efb86e624bdd28 that is the culprit.

The issue seems to be `fn_lim = os.pathconf(p, 'PC_NAME_MAX')` when there's a non-ASCII character present. I've tried an extremely simple and probably overly simplistic "fix" of changing that line to `fn_lim = os.pathconf(p.encode('utf-8'), 'PC_NAME_MAX')`. I'll see in a bit if it's working.

(I should probably instead make a test for this and just run that… would likely give results faster…)

**Comment by JoeLametta** [comment]
> The issue seems to be `fn_lim = os.pathconf(p, 'PC_NAME_MAX')` when there's a non-ASCII character present. I've tried an extremely simple and probably overly simplistic "fix" of changing that line to `fn_lim = os.pathconf(p.encode('utf-8'), 'PC_NAME_MAX')`.

That's the same conclusion I've come to. `Pathconf` expects bytes but `p` has type `unicode` (so it's not encoded). If not explicitly encoded, Python 2 will encode `p` using its default encoding: `ascii`. Explicitly encoding to `utf-8` should be the correct way to solve this issue.

As this issue is quite bad, I'm going to tag a new (minor) release after it has been fixed.

**Comment by Freso** [comment]
The rip went smoothly through with the previous suggested change. I tried removing the change and the ripping broke again. I submitted the change in https://github.com/whipper-team/whipper/pull/319

**Comment by Freso** [comment]
@JoeLametta Just a reminder to tag a new minor version. :)

**Comment by JoeLametta** [comment]
> @JoeLametta Just a reminder to tag a new minor version. :)

Done!

[whipper v0.7.2](https://github.com/whipper-team/whipper/releases/tag/v0.7.2)
