### ISSUE TITLE
Provide better error message when there's no CD in the drive

### ISSUE THREAD

**Issue by Freso** [whipper-team/whipper#385]
Currently `whipper cd rip` gives an ugly traceback if there's no CD in the tray/drive (see below). This should get caught and a nice(r!) message should be served to the user.

```python-traceback
> whipper cd rip -O "~/tmp/" -W "~/tmp/"
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr0
eject: Cd-rom-kommandoen luk skuffen mislykkedes: Inddata/uddata-fejl
Traceback (most recent call last):
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper/extern/task/task.py", line 521, in c
    callable_task(*args, **kwargs)
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper/program/cdrdao.py", line 111, in _read
    self._done()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper/program/cdrdao.py", line 149, in _done
    self.toc.parse()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper/image/toc.py", line 192, in parse
    handle = codecs.open(self._path, "r", "utf-8")
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/tmp/tmpjLqkLr.cdrdao.read-toc.whipper.task'
CRITICAL:whipper.command.main:exception IOError at /home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/codecs.py:898: open(): [Errno 2] No such file or directory: u'/tmp/tmpjLqkLr.cdrdao.read-toc.whipper.task'
Traceback (most recent call last):
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper/extern/task/task.py", line 521, in c
    callable_task(*args, **kwargs)
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper/program/cdrdao.py", line 111, in _read
    self._done()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper/program/cdrdao.py", line 149, in _done
    self.toc.parse()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper/image/toc.py", line 192, in parse
    handle = codecs.open(self._path, "r", "utf-8")
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/tmp/tmpjLqkLr.cdrdao.read-toc.whipper.task'
```

**Comment by JoeLametta** [comment]
I've found [this answer](https://superuser.com/a/1367091) which may help us solve this issue.

Relevant Linux Kernel documentation ([1](https://www.kernel.org/doc/Documentation/ioctl/cdrom.txt), [2](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/cdrom.h#n126), [3](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/cdrom.h#n395)):
```
    CDROM_DRIVE_STATUS		Get tray position, etc.

        usage:

        int slot;
        ioctl(fd, CDROM_DRIVE_STATUS, slot);

        inputs:
        Slot number to be tested, always zero except for jukeboxes.
        May also be special values CDSL_NONE or CDSL_CURRENT

        outputs:
        Ioctl return value will be one of the following values
        from <linux/cdrom.h>:

            CDS_NO_INFO		Information not available.
            CDS_NO_DISC
            CDS_TRAY_OPEN
            CDS_DRIVE_NOT_READY
            CDS_DISC_OK
            -1			error

        error returns:
        ENOSYS	Drive can't detect drive status
        EINVAL	Slot number beyond capacity of drive
        ENOMEM	Out of memory
```

```c
#define CDROM_DRIVE_STATUS	0x5326  /* Get tray position, etc. */
```

```c
/* drive status possibilities returned by CDROM_DRIVE_STATUS ioctl */
#define CDS_NO_INFO		0	/* if not implemented */
#define CDS_NO_DISC		1
#define CDS_TRAY_OPEN		2
#define CDS_DRIVE_NOT_READY	3
#define CDS_DISC_OK		4
```
