### ISSUE TITLE
whipper bails out if MusicBrainz release group doesn’t have a type

### ISSUE THREAD

**Issue by Freso** [whipper-team/whipper#396]
E.g., trying to rip a disc from [What’s Up? 8](https://musicbrainz.org/release/d8e6153a-2c47-4804-9d73-0aac1081c3b1) returns:
```python-traceback
> python2 -m whipper cd rip -O "~/tmp/" -W "~/tmp/"
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr0
eject: Cd-rom-kommandoen luk skuffen mislykkedes: Inddata/uddata-fejl
Track 1 finished, found 1148 Q sub-channels with CRC errors
Track 2 finished, found 2133 Q sub-channels with CRC errors
Track 3 finished, found 2410 Q sub-channels with CRC errors
Track 4 finished, found 1658 Q sub-channels with CRC errors
Track 5 finished, found 1448 Q sub-channels with CRC errors
Track 6 finished, found 1870 Q sub-channels with CRC errors
Track 7 finished, found 1462 Q sub-channels with CRC errors
Track 8 finished, found 1758 Q sub-channels with CRC errors
Track 9 finished, found 1895 Q sub-channels with CRC errors
Track 10 finished, found 4090 Q sub-channels with CRC errors
Track 11 finished, found 2242 Q sub-channels with CRC errors
Track 12 finished, found 3091 Q sub-channels with CRC errors
Track 13 finished, found 3135 Q sub-channels with CRC errors
Track 14 finished, found 1895 Q sub-channels with CRC errors
CDDB disc id: ca07ae0e
MusicBrainz disc id xu338_M8WukSRi0J.KTlDoflB8Y-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+14+147674+150+6650+17135+29982+37318+44334+53648+60998+69393+77732+96632+106946+121362+137085&tracks=14&id=xu338_M8WukSRi0J.KTlDoflB8Y-
Disc duration: 00:32:46.986, 14 audio tracks
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/freso/Development/Misc/whipper/whipper/__main__.py", line 14, in <module>
    sys.exit(main())
  File "whipper/command/main.py", line 43, in main
    ret = cmd.do()
  File "whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "whipper/command/cd.py", line 113, in do
    prompt=self.options.prompt)
  File "whipper/common/program.py", line 290, in getMusicBrainz
    record=self._record)
  File "whipper/common/mbngs.py", line 335, in musicbrainz
    md = _getMetadata(releaseDetail, discid, country)
  File "whipper/common/mbngs.py", line 185, in _getMetadata
    discMD.releaseType = release['release-group']['type']
KeyError: 'type'
```

**Comment by Freso** [comment]
Fixed with https://github.com/whipper-team/whipper/commit/885ad172a859e7b257c6c1581c7621f188f6951b (via https://github.com/whipper-team/whipper/pull/398).
