### ISSUE TITLE
Fix regression introduced due to Python 3 port

### ISSUE THREAD

**Issue by JoeLametta** [whipper-team/whipper#424]
After manual testing of this port, I've found a regression (everything else appears to be working fine).
Output:
```python
$ WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper image verify *.cue
Traceback (most recent call last):              
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.4.dev124+gc981ce2.d20191106', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python3.6/dist-packages/whipper-0.7.4.dev124+gc981ce2.d20191106-py3.6-linux-x86_64.egg/whipper/command/main.py", line 43, in main
    ret = cmd.do()
  File "/usr/local/lib/python3.6/dist-packages/whipper-0.7.4.dev124+gc981ce2.d20191106-py3.6-linux-x86_64.egg/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.6/dist-packages/whipper-0.7.4.dev124+gc981ce2.d20191106-py3.6-linux-x86_64.egg/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.6/dist-packages/whipper-0.7.4.dev124+gc981ce2.d20191106-py3.6-linux-x86_64.egg/whipper/command/image.py", line 61, in do
    verified = prog.verifyImage(runner, cueImage.table)
  File "/usr/local/lib/python3.6/dist-packages/whipper-0.7.4.dev124+gc981ce2.d20191106-py3.6-linux-x86_64.egg/whipper/common/program.py", line 561, in verifyImage
    responses = accurip.get_db_entry(table.accuraterip_path())
  File "/usr/local/lib/python3.6/dist-packages/whipper-0.7.4.dev124+gc981ce2.d20191106-py3.6-linux-x86_64.egg/whipper/image/table.py", line 828, in accuraterip_path
    discId1, discId2 = self.accuraterip_ids()
  File "/usr/local/lib/python3.6/dist-packages/whipper-0.7.4.dev124+gc981ce2.d20191106-py3.6-linux-x86_64.egg/whipper/image/table.py", line 822, in accuraterip_ids
    discId1 &= 0xffffffff
TypeError: unsupported operand type(s) for &=: 'float' and 'int'
```
Debug log:
```python
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.image.table:set logName
INFO:whipper.image.cue:parsing .cue file 'HTOA Test CD - DAE Drive Features Database.cue'
DEBUG:whipper.image.cue:found track 1
DEBUG:whipper.image.cue:found index 0 of track <Track 01> in './00. HTOA Test CD - Hidden Track One Audio.flac':0
DEBUG:whipper.image.cue:found index 1 of track <Track 01> in './01. HTOA Test CD - Music (In Pregap and Track).flac':0
DEBUG:whipper.image.image:setup image start
DEBUG:whipper.image.image:schedule scan of audio length of './00. HTOA Test CD - Hidden Track One Audio.flac'
DEBUG:whipper.image.image:verifying track 1
DEBUG:whipper.image.image:schedule scan of audio length of './01. HTOA Test CD - Music (In Pregap and Track).flac'
DEBUG:whipper.image.image:verifying image
DEBUG:whipper.extern.task.task:run task <whipper.image.image.ImageVerifyTask object at 0x7f77d37b3a20>
DEBUG:whipper.extern.task.task:Adding listener <whipper.extern.task.task.SyncRunner object at 0x7f77d37b36a0>
DEBUG:whipper.extern.task.task:run loop
DEBUG:whipper.extern.task.task:start task <whipper.image.image.ImageVerifyTask object at 0x7f77d37b3a20>
DEBUG:whipper.extern.task.task:MultiSeparateTask.start()
DEBUG:whipper.extern.task.task:starting
DEBUG:whipper.extern.task.task:notifying progress: 0.0 on 'Checking tracks'
DEBUG:whipper.extern.task.task:MultiSeparateTask.next()
DEBUG:whipper.extern.task.task:BaseMultiTask.next(): starting task 1 of 2: <whipper.program.soxi.AudioLengthTask object at 0x7f77d37b35c0>
DEBUG:whipper.extern.task.task:Adding listener <whipper.image.image.ImageVerifyTask object at 0x7f77d37b3a20>
DEBUG:whipper.extern.task.task:starting
DEBUG:whipper.extern.task.task:notifying progress: 0.0 on 'Getting length of audio track (1 of 2) ...'
DEBUG:whipper.extern.task.task:notifying progress: 0.0 on 'Getting length of audio track'
DEBUG:whipper.common.task:started ['soxi', '-s', './00. HTOA Test CD - Hidden Track One Audio.flac'] with pid 31609
DEBUG:whipper.extern.task.task:BaseMultiTask.next(): started task 1 of 2: <whipper.program.soxi.AudioLengthTask object at 0x7f77d37b35c0>
DEBUG:whipper.common.task:read from stdout: b'8305500\n'
DEBUG:whipper.common.task:return code was 0
DEBUG:whipper.extern.task.task:notifying progress: 1.0 on 'Getting length of audio track (1 of 2) ...'
DEBUG:whipper.extern.task.task:notifying progress: 1.0 on 'Getting length of audio track'
DEBUG:whipper.extern.task.task:stopping
DEBUG:whipper.extern.task.task:reset runner to None
DEBUG:whipper.extern.task.task:BaseMultiTask.stopped: task <whipper.program.soxi.AudioLengthTask object at 0x7f77d37b35c0> (1 of 2)
DEBUG:whipper.extern.task.task:BaseMultiTask.stopped: pick next task
DEBUG:whipper.extern.task.task:MultiSeparateTask.next()
DEBUG:whipper.extern.task.task:BaseMultiTask.next(): starting task 2 of 2: <whipper.program.soxi.AudioLengthTask object at 0x7f77d37b35f8>
DEBUG:whipper.extern.task.task:Adding listener <whipper.image.image.ImageVerifyTask object at 0x7f77d37b3a20>
DEBUG:whipper.extern.task.task:starting
DEBUG:whipper.extern.task.task:notifying progress: 0.0 on 'Getting length of audio track (2 of 2) ...'
DEBUG:whipper.extern.task.task:notifying progress: 0.0 on 'Getting length of audio track'
DEBUG:whipper.common.task:started ['soxi', '-s', './01. HTOA Test CD - Music (In Pregap and Track).flac'] with pid 31610
DEBUG:whipper.extern.task.task:BaseMultiTask.next(): started task 2 of 2: <whipper.program.soxi.AudioLengthTask object at 0x7f77d37b35f8>
DEBUG:whipper.common.task:read from stdout: b'10324104\n'
DEBUG:whipper.common.task:return code was 0
DEBUG:whipper.extern.task.task:notifying progress: 1.0 on 'Getting length of audio track (2 of 2) ...'
DEBUG:whipper.extern.task.task:notifying progress: 1.0 on 'Getting length of audio track'
DEBUG:whipper.extern.task.task:stopping
DEBUG:whipper.extern.task.task:reset runner to None
DEBUG:whipper.extern.task.task:BaseMultiTask.stopped: task <whipper.program.soxi.AudioLengthTask object at 0x7f77d37b35f8> (2 of 2)
DEBUG:whipper.extern.task.task:BaseMultiTask.stopped: all tasks done
DEBUG:whipper.extern.task.task:stopping
DEBUG:whipper.extern.task.task:reset runner to None
DEBUG:whipper.extern.task.task:stopped task <whipper.image.image.ImageVerifyTask object at 0x7f77d37b3a20>
DEBUG:whipper.extern.task.task:done running task <whipper.image.image.ImageVerifyTask object at 0x7f77d37b3a20>
DEBUG:whipper.image.image:verified image
DEBUG:whipper.image.table:set logName
DEBUG:whipper.image.image:setup image done
DEBUG:whipper.image.table:set logName
INFO:whipper.image.cue:parsing .cue file 'HTOA Test CD - DAE Drive Features Database.cue'
DEBUG:whipper.image.cue:found track 1
DEBUG:whipper.image.cue:found index 0 of track <Track 01> in './00. HTOA Test CD - Hidden Track One Audio.flac':0
DEBUG:whipper.image.cue:found index 1 of track <Track 01> in './01. HTOA Test CD - Music (In Pregap and Track).flac':0
DEBUG:whipper.image.image:schedule scan of audio length of './00. HTOA Test CD - Hidden Track One Audio.flac'
DEBUG:whipper.image.image:verifying track 1
DEBUG:whipper.image.image:schedule scan of audio length of './01. HTOA Test CD - Music (In Pregap and Track).flac'
DEBUG:whipper.extern.task.task:run task <whipper.image.image.ImageVerifyTask object at 0x7f77d37b30b8>
DEBUG:whipper.extern.task.task:Adding listener <whipper.extern.task.task.SyncRunner object at 0x7f77d37b36a0>
DEBUG:whipper.extern.task.task:run loop
DEBUG:whipper.extern.task.task:start task <whipper.image.image.ImageVerifyTask object at 0x7f77d37b30b8>
DEBUG:whipper.extern.task.task:MultiSeparateTask.start()
DEBUG:whipper.extern.task.task:starting
DEBUG:whipper.extern.task.task:notifying progress: 0.0 on 'Checking tracks'
DEBUG:whipper.extern.task.task:MultiSeparateTask.next()
DEBUG:whipper.extern.task.task:BaseMultiTask.next(): starting task 1 of 2: <whipper.program.soxi.AudioLengthTask object at 0x7f77d37b3e80>
DEBUG:whipper.extern.task.task:Adding listener <whipper.image.image.ImageVerifyTask object at 0x7f77d37b30b8>
DEBUG:whipper.extern.task.task:starting
DEBUG:whipper.extern.task.task:notifying progress: 0.0 on 'Getting length of audio track (1 of 2) ...'
DEBUG:whipper.extern.task.task:notifying progress: 0.0 on 'Getting length of audio track'
DEBUG:whipper.common.task:started ['soxi', '-s', './00. HTOA Test CD - Hidden Track One Audio.flac'] with pid 31611
DEBUG:whipper.extern.task.task:BaseMultiTask.next(): started task 1 of 2: <whipper.program.soxi.AudioLengthTask object at 0x7f77d37b3e80>
DEBUG:whipper.common.task:read from stdout: b'8305500\n'
DEBUG:whipper.common.task:return code was 0
DEBUG:whipper.extern.task.task:notifying progress: 1.0 on 'Getting length of audio track (1 of 2) ...'
DEBUG:whipper.extern.task.task:notifying progress: 1.0 on 'Getting length of audio track'
DEBUG:whipper.extern.task.task:stopping
DEBUG:whipper.extern.task.task:reset runner to None
DEBUG:whipper.extern.task.task:BaseMultiTask.stopped: task <whipper.program.soxi.AudioLengthTask object at 0x7f77d37b3e80> (1 of 2)
DEBUG:whipper.extern.task.task:BaseMultiTask.stopped: pick next task
DEBUG:whipper.extern.task.task:MultiSeparateTask.next()
DEBUG:whipper.extern.task.task:BaseMultiTask.next(): starting task 2 of 2: <whipper.program.soxi.AudioLengthTask object at 0x7f77d37b3cc0>
DEBUG:whipper.extern.task.task:Adding listener <whipper.image.image.ImageVerifyTask object at 0x7f77d37b30b8>
DEBUG:whipper.extern.task.task:starting
DEBUG:whipper.extern.task.task:notifying progress: 0.0 on 'Getting length of audio track (2 of 2) ...'
DEBUG:whipper.extern.task.task:notifying progress: 0.0 on 'Getting length of audio track'
DEBUG:whipper.common.task:started ['soxi', '-s', './01. HTOA Test CD - Music (In Pregap and Track).flac'] with pid 31612
DEBUG:whipper.extern.task.task:BaseMultiTask.next(): started task 2 of 2: <whipper.program.soxi.AudioLengthTask object at 0x7f77d37b3cc0>
DEBUG:whipper.common.task:read from stdout: b'10324104\n'
DEBUG:whipper.common.task:return code was 0
DEBUG:whipper.extern.task.task:notifying progress: 1.0 on 'Getting length of audio track (2 of 2) ...'
DEBUG:whipper.extern.task.task:notifying progress: 1.0 on 'Getting length of audio track'
DEBUG:whipper.extern.task.task:stopping
DEBUG:whipper.extern.task.task:reset runner to None
DEBUG:whipper.extern.task.task:BaseMultiTask.stopped: task <whipper.program.soxi.AudioLengthTask object at 0x7f77d37b3cc0> (2 of 2)
DEBUG:whipper.extern.task.task:BaseMultiTask.stopped: all tasks done
DEBUG:whipper.extern.task.task:stopping
DEBUG:whipper.extern.task.task:reset runner to None
DEBUG:whipper.extern.task.task:stopped task <whipper.image.image.ImageVerifyTask object at 0x7f77d37b30b8>
DEBUG:whipper.extern.task.task:done running task <whipper.image.image.ImageVerifyTask object at 0x7f77d37b30b8>
```

Code of the relevant section:
https://github.com/whipper-team/whipper/blob/f6dcc08e3f41419ad5a53a286243eb35badc6b38/whipper/image/table.py#L799-L825

It seems that the `offset` is a float (`int.0`).
The value of the `offset` comes either from `offset = self.getTrackStart(track.number)`, relevant code here:
https://github.com/whipper-team/whipper/blob/f6dcc08e3f41419ad5a53a286243eb35badc6b38/whipper/image/table.py#L194-L203

or from `offset = self.getTrackEnd(self.tracks[-1].number) + 1`, relevant code here:
https://github.com/whipper-team/whipper/blob/f6dcc08e3f41419ad5a53a286243eb35badc6b38/whipper/image/table.py#L205-L227

In both cases what's alarming is that the float value seems to originate from the `self.tracks[number].getIndex(index).absolute` call. I don't know why that one is a float but it should be an int.
If I run the same command using whipper's code from `develop` branch (commit f740a0ef0d4503b16485b417d1222032a20cd4b6) against the same files, it completes successfully.

This can be replicated using the files included in [this ZIP archive](https://linx.li/hqjmy3se.zip) but I don't think it depends on these specific files.

_Originally posted by @JoeLametta in https://github.com/whipper-team/whipper/pull/411#issuecomment-550374113_

**Comment by MerlijnWajer** [comment]
```
diff --git a/whipper/image/image.py b/whipper/image/image.py
index c68a6f0..1d2251c 100644
--- a/whipper/image/image.py
+++ b/whipper/image/image.py
@@ -167,7 +167,7 @@ class ImageVerifyTask(task.MultiSeparateTask):
                                  "in debug log (set RIP_DEBUG=4)")
             index = track.indexes[1]
             assert taskk.length % common.SAMPLES_PER_FRAME == 0
-            end = taskk.length / common.SAMPLES_PER_FRAME
+            end = taskk.length // common.SAMPLES_PER_FRAME
             self.lengths[trackIndex] = end - index.relative
 
```
