### ISSUE TITLE
configparser Error

### ISSUE THREAD

**Issue by Aquan1412** [whipper-team/whipper#443]
[whipper.log.gz](https://github.com/whipper-team/whipper/files/4020453/whipper.log.gz)
When I try to use whipper to rip a cd I always get a configparser error:

```python
~ >>> whipper cd rip
INFO:whipper.command.cd:using configured read offset 103
Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.9.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python3.8/site-packages/whipper/command/main.py", line 42, in main
    cmd = Whipper(sys.argv[1:], os.path.basename(sys.argv[0]), None)
  File "/usr/lib/python3.8/site-packages/whipper/command/basecommand.py", line 114, in __init__
    self.cmd = self.subcommands[self.options.remainder[0]](
  File "/usr/lib/python3.8/site-packages/whipper/command/basecommand.py", line 114, in __init__
    self.cmd = self.subcommands[self.options.remainder[0]](
  File "/usr/lib/python3.8/site-packages/whipper/command/basecommand.py", line 67, in __init__
    val = config.Config().get(config_section, action.dest)
  File "/usr/lib/python3.8/site-packages/whipper/common/config.py", line 70, in get
    return self._getter('', section, option)
  File "/usr/lib/python3.8/site-packages/whipper/common/config.py", line 65, in _getter
    return method(section, option)
  File "/usr/lib/python3.8/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/usr/lib/python3.8/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.8/configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: "%' must be represented '%%'"
```

Steps to reproduce the error:
1) run whipper cd rip

I'm using Manjaro Linux and installed whipper from the "community" repository.
I didn't change the default config file (apart from adjusting the drive offset), so it currently looks like this:

```INI
[whipper.cd.rip]
unknown = True
output_directory = ~/Musik
track_template = new/%%A/%%y - %%d/%%t - %%n	; note: the format char '%' must be represented '%%'
disc_template = %(track_template)s
```

Any ideas what might be the problem?

**Comment by JoeLametta** [comment]
Hi, could you try to just remove the `disc_template` line (or replace it with the one in the README) from whipper's config file and see if the issue is solved?

**Comment by Aquan1412** [comment]
Thank you, that was one part of the problem. The other part was, that apparently also the mention of '%' in comments isn't allowed, so I also had to remove the comment behind track template before it worked.

**Comment by JoeLametta** [comment]
Thanks, fixed the bug about the `InterpolationSyntaxError` caused by  the `%` character in the inline comment with commit 150f0d5e91b1f38ad690225cb6051df33030a932.
