### ISSUE TITLE
Unable to rip CD with extremely long title

### ISSUE THREAD

**Issue by the-confessor** [whipper-team/whipper#453]
I've run into a problem ripping a CD with an [extremely long title](https://musicbrainz.org/release/9d2c19ac-4890-4720-92dc-ed33f86c8438).

Doing some digging I noticed an existing issue #197 - it says milestone is 1.0 but in whipper 0.9.0 there seems to already be some kind of truncate_filename method introduced. So I am wondering if that fix is in there already, but just not working in this scenario?

The error I encounter:

```
Track 13 finished, found 21 Q sub-channels with CRC errors
Track 14 finished, found 26 Q sub-channels with CRC errors
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/whipper/extern/task/task.py", line 518, in c
    callable_task(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/whipper/program/cdrdao.py", line 111, in _read
    self._done()
  File "/usr/lib64/python3.6/site-packages/whipper/program/cdrdao.py", line 154, in _done
    os.makedirs(t_dirn, exist_ok=True)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: "/media/music/Soulwax - Most of the remixes we've made for other people over the years except for the one for Einstürzende Neubauten because we lost it and a few we didn't think sounded good enough or just didn't fit in length-wise, but including some that are hard to find because either people forgot about them or just simply because they haven't been released yet, a few we really love, one we think is just ok, some we did for free, some we did for money, some for ourselves without permission and some for friends as swaps but never on time and always at our studio in Ghent. - Unmixed"
CRITICAL:whipper.command.main:exception OSError at /usr/lib64/python3.6/os.py:220: makedirs(): [Errno 36] File name too long: "/media/music/Soulwax - Most of the remixes we've made for other people over the years except for the one for Einstürzende Neubauten because we lost it and a few we didn't think sounded good enough or just didn't fit in length-wise, but including some that are hard to find because either people forgot about them or just simply because they haven't been released yet, a few we really love, one we think is just ok, some we did for free, some we did for money, some for ourselves without permission and some for friends as swaps but never on time and always at our studio in Ghent. - Unmixed"
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/whipper/extern/task/task.py", line 518, in c
    callable_task(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/whipper/program/cdrdao.py", line 111, in _read
    self._done()
  File "/usr/lib64/python3.6/site-packages/whipper/program/cdrdao.py", line 154, in _done
    os.makedirs(t_dirn, exist_ok=True)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: "/media/music/Soulwax - Most of the remixes we've made for other people over the years except for the one for Einstürzende Neubauten because we lost it and a few we didn't think sounded good enough or just didn't fit in length-wise, but including some that are hard to find because either people forgot about them or just simply because they haven't been released yet, a few we really love, one we think is just ok, some we did for free, some we did for money, some for ourselves without permission and some for friends as swaps but never on time and always at our studio in Ghent. - Unmixed"

### looking for pattern: INFO:whipper\.image\.cue:parsing \.cue file ['"].*.cue['"] in /home/ed/logs/audio-rip/rip-2020-01-18T13-10-22.log
### result: success (but couldn't find output folder for further processing)
```

**Comment by JoeLametta** [comment]
@the-confessor Hi, I've just commited an untested fix in 151f6c8a4f30182ff7735198ec19ae61b8573c38 (in a custom branch): could you try if [that one](https://github.com/whipper-team/whipper/commit/151f6c8a4f30182ff7735198ec19ae61b8573c38.patch) fixes your issue?

Thanks,
Joe

**Comment by the-confessor** [comment]
I applied that patch and the result is the same - exact same stack trace. 

I notice that the patch is in cd.py, which doesn't appear in the stack trace.

**Comment by the-confessor** [comment]
Update - not only does it not fix the issue, it seems to have other side effects, e.g. here is the output of [another CD](https://musicbrainz.org/release/778e1560-f3fd-4a34-898e-6eb2fc0a79bd) rip with that patch applied:

```
MGMT -.cue
MGMT -.m3u
MGMT - Oracular.flac
MGMT - Oracular Spectacular - 06 - 4th Dimensional.flac
MGMT - Oracular Spectacular - 08 - Of Moons, Birds &.flac
MGMT -.score
MGMT -.toc
```

My templates:

```
track_template="%A - %d/%A - %d - %t - %n"
disc_template="%A - %d/%A - %d"
```

**Comment by JoeLametta** [comment]
Thanks for the reply.
I've discovered that the `shrinkPath()` method we're using is quite useless.
A comprehensive way to verify a path doesn't exceed any limit in Python would be this:

```python
import os

def check_path_length(path):
    """
    Check whether the path and its components respect the filesystem limits.

    This method assumes the provided path has been normalized.

    The limits retrieved aren't always reliable as some platforms
    may provide deceptive values.

    NOTE: os.pathconf() is only available on Unix.

    :var path: normalized path
    :type path: str
    :returns: True if length of path and its components respect the filesystem
              limits, False otherwise
    :rtype: bool
    """
    components = path.split(os.sep)
    comp_max_len = len(max(components, key=len).encode())
    fn_lim = pathconf(path.encode(), 'PC_NAME_MAX')
    path_lim = pathconf(path.encode(), 'PC_PATH_MAX')
    return comp_max_len <= fn_lim and len(path.encode()) <= path_lim
```

I think that the method `truncate_filename()` works fine but it only applies to the last portion of the path (filename).

What's needed to do to truly address this issue is:
1. Check that the destination path (without template) respects the limits of the filesystem. If it doesn't, raise a meaningful error.
2. Implement a function which knowing the basepath (portion before template) and the last path (template + filename) tries to return a shrinked path it in a meaningful way to respect the limits of the filesystem.

For example on Linux it seems that any component of the path can't be longer than 255 bytes so the function should take care of this (shrinking) for any of the components.
The limit for a complete path is something like 4096 bytes which, I would say, it's quite difficult to reach for a normal use case.

**Comment by srussel** [comment]
This is a case that would benefit from #342. Even after truncating to filesystem limits, I don't think I would be happy with a 255 character file or directory name. Some music players may still choke on it and it may be an issue copying to a different filesystem.

**Comment by the-confessor** [comment]
It is quite a challenging problem, and I agree #342 would at least provide a workaround.

**Comment by JoeLametta** [comment]
In addition to the filesystem limits check we could add a feature to provide users a way to set more restrictive limits which would allow shrinking the paths even more.

**Comment by srussel** [comment]
This patch is a hack I have been using for a few months to work around this issue. It adds an "--edit" option that writes the metadata to a text file, opens it in an editor for the user to update, then parses it back into whipper before continuing with the rip.

[whipper-edit-metadata.txt](https://github.com/whipper-team/whipper/files/5790229/whipper-edit-metadata.txt)

**Comment by Waiwei8k** [comment]
I'm seeing the same problem:

`Starting Whipper
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr2
WARNING:whipper.program.utils:command 'eject -t /dev/sr2' returned with exit code '1' (b'eject: CD-ROM tray close command failed: No such file or directory')
CDDB disc id: f90c7c13
MusicBrainz disc id FIbSg5ZCs2bZYUS_NzY9TTIqb4U-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+19+264912+25273+40256+56467+72499+79813+91620+107352+116369+123166+137757+150395+161472+168674+183077+197130+207171+214853+240078+246754&tracks=19&id=FIbSg5ZCs2bZYUS_NzY9TTIqb4U-
Disc duration: 00:53:15.186, 19 audio tracks

Matching releases:

Artist  : Soulwax
Title   : Most of the remixes we’ve made for other people over the years except for the one for Einstürzende Neubauten because we lost it and a few we didn’t think sounded good enough or just didn’t fit in length-wise, but including some that are hard to find because either people forgot about them or just simply because they haven’t been released yet, a few we really love, one we think is just ok, some we did for free, some we did for money, some for ourselves without permission and some for friends as swaps but never on time and always at our studio in Ghent. (Disc 2 of 2): Mixed by 2manydjs
Duration: 00:53:16.000
URL     : https://musicbrainz.org/release/3d84e4e0-2044-4ca4-8cd2-1d759331857d
Release : 3d84e4e0-2044-4ca4-8cd2-1d759331857d
Type    : Compilation
Barcode : 5099950924721
Country : United Kingdom
Cat no  : 509 2472

Artist  : Soulwax
Title   : Most of the remixes we’ve made for other people over the years except for the one for Einstürzende Neubauten because we lost it and a few we didn’t think sounded good enough or just didn’t fit in length-wise, but including some that are hard to find because either people forgot about them or just simply because they haven’t been released yet, a few we really love, one we think is just ok, some we did for free, some we did for money, some for ourselves without permission and some for friends as swaps but never on time and always at our studio in Ghent. (Disc 2 of 2): Mixed by 2manydjs
Duration: 00:53:16.000
URL     : https://musicbrainz.org/release/9d2c19ac-4890-4720-92dc-ed33f86c8438
Release : 9d2c19ac-4890-4720-92dc-ed33f86c8438
Type    : Compilation
Barcode : 5099951098629
Country : United Kingdom
Cat no  : 509995 1098629

Track 1 finished, found 5 Q sub-channels with CRC errors
Track 2 finished, found 7 Q sub-channels with CRC errors
Track 3 finished, found 4 Q sub-channels with CRC errors
Track 4 finished, found 20 Q sub-channels with CRC errors
Track 5 finished, found 7 Q sub-channels with CRC errors
Track 6 finished, found 4 Q sub-channels with CRC errors
Track 8 finished, found 2 Q sub-channels with CRC errors
Track 9 finished, found 1 Q sub-channels with CRC errors
Track 11 finished, found 2 Q sub-channels with CRC errors
Track 13 finished, found 4 Q sub-channels with CRC errors
Track 14 finished, found 2 Q sub-channels with CRC errors
Track 15 finished, found 1 Q sub-channels with CRC errors
Track 16 finished, found 2 Q sub-channels with CRC errors
Track 17 finished, found 7 Q sub-channels with CRC errors
Track 19 finished, found 8 Q sub-channels with CRC errors
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/usr/lib/python3/dist-packages/whipper/program/cdrdao.py", line 159, in _done
    os.makedirs(t_dirn)
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 36] File name too long: '/raid/md0/scratch/whipper/enc/1072efDf29C0B8A2a7819b40dD9d5A8b/compilation/Soulwax - Most of the remixes we’ve made for other people over the years except for the one for Einstürzende Neubauten because we lost it and a few we didn’t think sounded good enough or just didn’t fit in length-wise, but including some that are hard to find because either people forgot about them or just simply because they haven’t been released yet, a few we really love, one we think is just ok, some we did for free, some we did for money, some for ourselves without permission and some for friends as swaps but never on time and always at our studio in Ghent. (Disc 2 of 2): Mixed by 2manydjs'
CRITICAL:whipper.command.main:exception OSError at <frozen os>:225: makedirs(): [Errno 36] File name too long: '/raid/md0/scratch/whipper/enc/1072efDf29C0B8A2a7819b40dD9d5A8b/compilation/Soulwax - Most of the remixes we’ve made for other people over the years except for the one for Einstürzende Neubauten because we lost it and a few we didn’t think sounded good enough or just didn’t fit in length-wise, but including some that are hard to find because either people forgot about them or just simply because they haven’t been released yet, a few we really love, one we think is just ok, some we did for free, some we did for money, some for ourselves without permission and some for friends as swaps but never on time and always at our studio in Ghent. (Disc 2 of 2): Mixed by 2manydjs'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/usr/lib/python3/dist-packages/whipper/program/cdrdao.py", line 159, in _done
    os.makedirs(t_dirn)
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 36] File name too long: '/raid/md0/scratch/whipper/enc/1072efDf29C0B8A2a7819b40dD9d5A8b/compilation/Soulwax - Most of the remixes we’ve made for other people over the years except for the one for Einstürzende Neubauten because we lost it and a few we didn’t think sounded good enough or just didn’t fit in length-wise, but including some that are hard to find because either people forgot about them or just simply because they haven’t been released yet, a few we really love, one we think is just ok, some we did for free, some we did for money, some for ourselves without permission and some for friends as swaps but never on time and always at our studio in Ghent. (Disc 2 of 2): Mixed by 2manydjs'
`

**Comment by Waiwei8k** [comment]
I still have this issue with whipper 0.10.0.

**Comment by Waiwei8k** [comment]
As a workaround, I ripped this CD by disabling my network connection and passing -U to allow unknown CDs.

**Comment by LIII-XXII** [comment]
Same issue here, but on creation of the folder:
```
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/whipper/program/cdrdao.py", line 115, in _read
    self._done()
    ~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/whipper/program/cdrdao.py", line 159, in _done
    os.makedirs(t_dirn)
    ~~~~~~~~~~~^^^^^^^^
  File "<frozen os>", line 228, in makedirs
OSError: [Errno 36] File name too long: '<really long folder name>'
CRITICAL:whipper.command.main:exception OSError at <frozen os>:228: makedirs(): [Errno 36] File name too long: '<really long folder name>'
```
