### ISSUE TITLE
KeyError: Invalid MusicBrainz server

### ISSUE THREAD

**Issue by ghcatt** [whipper-team/whipper#472]
getting this error with an old configfile and whipper 0.9:

```
whipper cd rip
Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.9.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python3.8/site-packages/whipper/command/main.py", line 22, in main
    server = config.Config().get_musicbrainz_server()
  File "/usr/lib/python3.8/site-packages/whipper/common/config.py", line 81, in get_musicbrainz_server
    raise KeyError('Invalid MusicBrainz server: %s' % server)
KeyError: 'Invalid MusicBrainz server: https://musicbrainz.org\t; use MusicBrainz server at host[:port]'

```

whipper.conf:

```
# HOWTO setup your CD drive for whipper:
# - Select a common undamaged disc
# - Add CD drive details to the whipper config with: whipper drive analyze
# - Add  known drive offset value in whipper.conf (read_offset = #), or detect offset with: whipper offset find
# - Confirm desired configuration file options, including output directory and variables for disc and track naming.

#Tracks are named according to the track template, filling in the variables
#and adding the file extension.  Variables exclusive to the track template are:
# - %t: track number
# - %a: track artist
# - %n: track title
# - %s: track sort name

#Disc files (.cue, .log, .m3u) are named according to the disc template,
#filling in the variables and adding the file extension. Variables for both
#disc and track template are:
# - %A: album artist
# - %S: album sort name
# - %d: disc title
# - %y: release year
# - %r: release type, lowercase
# - %R: Release type, normal case
# - %x: audio extension, lowercase
# - %X: audio extension, uppercase


[main]
path_filter_dot = True			; replace leading dot with _
path_filter_posix = True		; replace illegal chars in *nix OSes with _
path_filter_vfat = False		; replace illegal chars in VFAT filesystems with _
path_filter_whitespace = False		; replace all whitespace chars with _
path_filter_printable = False		; replace all non printable ASCII chars with _

[musicbrainz]
server = https://musicbrainz.org	; use MusicBrainz server at host[:port]
# use http as scheme if connecting to a plain http server. Example below:
# server = http://example.com:8080

[drive:hp%20%20%20%20%20%20%3ACDDVDW%20SU-208CB%20%3AHH00]
vendor = hp
model = CDDVDW SU-208CB
release = HH00
defeats_cache = True		; whether the drive is capable of defeating the audio cache
read_offset = 6			; drive read offset in positive/negative frames (no leading +)
# do not edit the values 'vendor', 'model', and 'release'; they are used by whipper to match the drive

# command line defaults for `whipper cd rip`
[whipper.cd.rip]
cdr = True
unknown = True
force_overread = False
logger = whipper
output_directory = ~/My Music
# Note: the format char '%' must be represented '%%'.
# Do not add inline comments with an unescaped '%' character (else an 'InterpolationSyntaxError' will occur).
track_template = new/%%A/%%y - %%d/%%t - %%n
disc_template =  new/%%A/%%y - %%d/%%A - %%d
# ...
```

i tried to stay close to the example config file of the documentation. the musicbrainz section is identical.

**Comment by JoeLametta** [comment]
Hi, this happens because the README shown on GitHub is sourced from the `develop` branch which often contains code which hasn't been released as a tagged version of whipper yet.
The allowed values of that option have been redefined in a way which isn't backward compatible in pull request #450. Before that one `server` was defined like this:

> `server`: the MusicBrainz server to connect to, in `host:[port]` format. Defaults to `musicbrainz.org`.

My advice is to remove the `[musicbrainz]` section completely from your config file if you're not interested in defining a custom server. That should solve your error.

**Comment by ghcatt** [comment]
thanks for replying.

ok, so i commented the musicbrainz section and ran once more: whipper cd rip

unfortunately, no luck.


```
Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.9.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python3.8/site-packages/whipper/command/main.py", line 42, in main
    cmd = Whipper(sys.argv[1:], os.path.basename(sys.argv[0]), None)
  File "/usr/lib/python3.8/site-packages/whipper/command/basecommand.py", line 114, in __init__
    self.cmd = self.subcommands[self.options.remainder[0]](
  File "/usr/lib/python3.8/site-packages/whipper/command/basecommand.py", line 114, in __init__
    self.cmd = self.subcommands[self.options.remainder[0]](
  File "/usr/lib/python3.8/site-packages/whipper/command/basecommand.py", line 60, in __init__
    self.add_arguments()
  File "/usr/lib/python3.8/site-packages/whipper/command/cd.py", line 241, in add_arguments
    default_offset = config.Config().getReadOffset(*info)
  File "/usr/lib/python3.8/site-packages/whipper/common/config.py", line 103, in getReadOffset
    return int(self._parser.get(section, 'read_offset'))
ValueError: invalid literal for int() with base 10: '6\t\t\t; drive read offset in positive/negative frames (no leading +)'
```

there seems to be an error with the read offset - my drive definitely has +6.
