### ISSUE TITLE
cdparanoia couldn't read any frames

### ISSUE THREAD

**Issue by shibumi** [whipper-team/whipper#474]
Whipper Version: 0.9.0
OS: Arch Linux

Hi I've received the following output:
```
INFO:whipper.command.cd:using configured read offset 103
INFO:whipper.command.cd:checking device /dev/sr0
CDDB disc id: 930c0e0c
MusicBrainz disc id C7heQH0k6jUyn_y92k4ublrpU2M-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+12+231600+150+16970+36185+57570+75200+94475+114265+131990+153890+171080+187570+207430&tracks=12&id=C7heQH0k6jUyn_y92k4ublrpU2M-
Disc duration: 00:51:26.000, 12 audio tracks

Matching releases:

Artist  : SCANDAL
Title   : Kiss from the darkness (通常盤)
Duration: 00:51:28.796
URL     : https://musicbrainz.org/release/068535c5-ff6d-49df-a1ee-2757e05e71ff
Release : 068535c5-ff6d-49df-a1ee-2757e05e71ff
Type    : Album
Barcode : 4988002799282
Cat no  : VICL-65310

Track 1 finished, found 1 Q sub-channels with CRC errors
Track 3 finished, found 2 Q sub-channels with CRC errors
Track 4 finished, found 1 Q sub-channels with CRC errors
Track 5 finished, found 61 Q sub-channels with CRC errors
Track 7 finished, found 2 Q sub-channels with CRC errors
Track 8 finished, found 3 Q sub-channels with CRC errors
Track 9 finished, found 2 Q sub-channels with CRC errors
Track 10 finished, found 23 Q sub-channels with CRC errors
INFO:whipper.command.cd:ripping track 1 of 12: 01. SCANDAL - Tonight.flac
INFO:whipper.program.cdparanoia:checksums match, d5938563
INFO:whipper.command.cd:CRCs match for track 1
Peak level: 0.998840
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 2 of 12: 02. SCANDAL - マスターピース.flac
INFO:whipper.program.cdparanoia:checksums match, af48ce66
INFO:whipper.command.cd:CRCs match for track 2
Peak level: 0.998840
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 3 of 12: 03. SCANDAL - Fuzzy.flac
INFO:whipper.program.cdparanoia:checksums match, d1f87846
INFO:whipper.command.cd:CRCs match for track 3
Peak level: 0.998840
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 4 of 12: 04. SCANDAL - 最終兵器、君.flac
INFO:whipper.program.cdparanoia:checksums match, 69348439
INFO:whipper.command.cd:CRCs match for track 4
Peak level: 0.998840
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 5 of 12: 05. SCANDAL - ランドリーランドリー.flac
INFO:whipper.program.cdparanoia:checksums match, d0a931cf
INFO:whipper.command.cd:CRCs match for track 5
Peak level: 0.998840
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 6 of 12: 06. SCANDAL - NEON TOWN ESCAPE.flac
INFO:whipper.program.cdparanoia:checksums match, a8b440c7
INFO:whipper.command.cd:CRCs match for track 6
Peak level: 0.998840
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 7 of 12: 07. SCANDAL - セラミックブルー.flac
INFO:whipper.program.cdparanoia:checksums match, 34cc20cd
INFO:whipper.command.cd:CRCs match for track 7
Peak level: 0.998840
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 8 of 12: 08. SCANDAL - 記念日.flac
INFO:whipper.program.cdparanoia:checksums match, 5b661b67
INFO:whipper.command.cd:CRCs match for track 8
Peak level: 0.998840
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 9 of 12: 09. SCANDAL - まばたき.flac
INFO:whipper.program.cdparanoia:checksums match, 7b8f7ee5
INFO:whipper.command.cd:CRCs match for track 9
Peak level: 0.998840
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 10 of 12: 10. SCANDAL - A.M.D.K.J..flac
INFO:whipper.program.cdparanoia:checksums match, da2bb1c1
INFO:whipper.command.cd:CRCs match for track 10
Peak level: 0.998840
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 11 of 12: 11. SCANDAL - 月.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 46710764
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Traceback (most recent call last):         
  File "/usr/lib/python3.8/site-packages/whipper/program/cdparanoia.py", line 197, in getTrackQuality
    return min(frames * 2.0 / reads, 1.0)
ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/whipper/extern/task/task.py", line 518, in c
    callable_task(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/whipper/program/cdparanoia.py", line 312, in _read
    self._done()
  File "/usr/lib/python3.8/site-packages/whipper/program/cdparanoia.py", line 388, in _done
    self.quality = self._parser.getTrackQuality()
  File "/usr/lib/python3.8/site-packages/whipper/program/cdparanoia.py", line 199, in getTrackQuality
    raise RuntimeError("cdparanoia couldn't read any frames "
RuntimeError: cdparanoia couldn't read any frames for the current track
INFO:whipper.command.cd:ripping track 11 of 12 (try 2): 11. SCANDAL - 月.flac
INFO:whipper.program.cdparanoia:checksums match, 64bc2ae0
INFO:whipper.command.cd:CRCs match for track 11    
Peak level: 0.998840
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 12 of 12: 12. SCANDAL - YOU GO GIRL!.flac
INFO:whipper.program.cdparanoia:checksums match, 60810a03
INFO:whipper.command.cd:CRCs match for track 12    
Peak level: 0.998840
Rip quality: 100.00%
INFO:whipper.image.cue:parsing .cue file 'album/SCANDAL - Kiss from the darkness (通常盤)/SCANDAL - Kiss from the darkness (通常盤).cue'
ERROR:whipper.common.accurip:error retrieving AccurateRip entry: 404 Not Found <Response [404]>
WARNING:whipper.common.accurip:entry not found in AccurateRip database
WARNING:whipper.command.cd:AccurateRip entry not found
ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 1
track  1: unknown          (error)
ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 2
track  2: unknown          (error)
ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 3
track  3: unknown          (error)
ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 4
track  4: unknown          (error)
ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 5
track  5: unknown          (error)
ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 6
track  6: unknown          (error)
ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 7
track  7: unknown          (error)
ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 8
track  8: unknown          (error)
ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 9
track  9: unknown          (error)
ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 10
track 10: unknown          (error)
ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 11
track 11: unknown          (error)
ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 12
track 12: unknown          (error)
'whipper cd rip' time: 46:15.37s, cpu: 5%
```

I've tried to reproduce this via: `WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper cd rip`, but a second rip just gave me this:

```
CDDB disc id: 930c0e0c
MusicBrainz disc id C7heQH0k6jUyn_y92k4ublrpU2M-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+12+231600+150+16970+36185+57570+75200+94475+114265+131990+153890+171080+187570+207430&tracks=12&id=C7heQH0k6jUyn_y92k4ublrpU2M-
Disc duration: 00:51:26.000, 12 audio tracks

Matching releases:

Artist  : SCANDAL
Title   : Kiss from the darkness (通常盤)
Duration: 00:51:28.796
URL     : https://musicbrainz.org/release/068535c5-ff6d-49df-a1ee-2757e05e71ff
Release : 068535c5-ff6d-49df-a1ee-2757e05e71ff
Type    : Album
Barcode : 4988002799282
Cat no  : VICL-65310

Peak level: 0.998840                      
Rip quality: 100.00%
Peak level: 0.998840                      
Rip quality: 100.00%
Peak level: 0.998840                      
Rip quality: 100.00%
Peak level: 0.998840                      
Rip quality: 100.00%
Peak level: 0.998840                      
Rip quality: 100.00%
Peak level: 0.998840                      
Rip quality: 100.00%
Peak level: 0.998840                      
Rip quality: 100.00%
Peak level: 0.998840                      
Rip quality: 100.00%
Peak level: 0.998840                      
Rip quality: 100.00%
Peak level: 0.998840                       
Rip quality: 100.00%
Peak level: 0.998840                       
Rip quality: 100.00%
Peak level: 0.998840                       
Rip quality: 100.00%
track  1: unknown          (error)                
track  2: unknown          (error)
track  3: unknown          (error)
track  4: unknown          (error)
track  5: unknown          (error)
track  6: unknown          (error)
track  7: unknown          (error)
track  8: unknown          (error)
track  9: unknown          (error)
track 10: unknown          (error)
track 11: unknown          (error)
track 12: unknown          (error)
```

+ no mention of such python errors in the debug log.

**Comment by Viktini** [comment]
I get the same error but when trying to let it configure the offset.

OS: Gentoo Linux (Linux 5.5.8-gentoo-x86_64)
Whipper version: 0.9.0

```
INFO:whipper.command.offset:checking device /dev/sr0                                                                                                                                                               
WARNING:whipper.program.utils:command 'eject -t /dev/sr0' returned with exit code '1' (b'eject: CD-ROM tray close command failed: Input/output error')                                                             
Track 1 finished, found 2 Q sub-channels with CRC errors                                                                                                                                                           
Track 2 finished, found 4 Q sub-channels with CRC errors                                                                                                                                                           
Track 3 finished, found 3 Q sub-channels with CRC errors                                                                                                                                                           
Track 4 finished, found 5 Q sub-channels with CRC errors                                                                                                                                                           
Track 5 finished, found 1 Q sub-channels with CRC errors                                                                                                                                                           
Track 6 finished, found 4 Q sub-channels with CRC errors                                                                                                                                                           
Track 7 finished, found 2 Q sub-channels with CRC errors                                                                                                                                                           
Track 8 finished, found 6 Q sub-channels with CRC errors                                                                                                                                                           
Track 9 finished, found 1 Q sub-channels with CRC errors                                                                                                                                                           
Track 10 finished, found 5 Q sub-channels with CRC errors                                                                                                                                                          
Track 11 finished, found 7 Q sub-channels with CRC errors                                                                                                                                                          
Track 12 finished, found 1039 Q sub-channels with CRC errors                                                                                                                                                       
Track 13 finished, found 313 Q sub-channels with CRC errors                                                                                                                                                        
Track 14 finished, found 10 Q sub-channels with CRC errors                                                                                                                                                         
Track 15 finished, found 25 Q sub-channels with CRC errors                                                                                                                                                         
INFO:whipper.command.offset:trying read offset 667...                                                                                                                                                              
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 18964220                                                                                                                                
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/lib64/python3.6/site-packages/whipper/program/cdparanoia.py", line 197, in getTrackQuality                                                                                                            
    return min(frames * 2.0 / reads, 1.0)
ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/whipper/extern/task/task.py", line 518, in c
    callable_task(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/whipper/program/cdparanoia.py", line 312, in _read
    self._done()
  File "/usr/lib64/python3.6/site-packages/whipper/program/cdparanoia.py", line 388, in _done
    self.quality = self._parser.getTrackQuality()
  File "/usr/lib64/python3.6/site-packages/whipper/program/cdparanoia.py", line 199, in getTrackQuality
    raise RuntimeError("cdparanoia couldn't read any frames "
RuntimeError: cdparanoia couldn't read any frames for the current track
WARNING:whipper.command.offset:unknown task exception for offset 667: (RuntimeError("cdparanoia couldn't read any frames for the current track",), 'exception RuntimeError at /usr/lib64/python3.6/site-packages/wh
ipper/program/cdparanoia.py:199: getTrackQuality(): cdparanoia couldn\'t read any frames for the current track\nTraceback (most recent call last):\n  File "/usr/lib64/python3.6/site-packages/whipper/program/cdpa
ranoia.py", line 197, in getTrackQuality\n    return min(frames * 2.0 / reads, 1.0)\nZeroDivisionError: float division by zero\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback 
(most recent call last):\n  File "/usr/lib64/python3.6/site-packages/whipper/extern/task/task.py", line 518, in c\n    callable_task(*args, **kwargs)\n  File "/usr/lib64/python3.6/site-packages/whipper/program/c
dparanoia.py", line 312, in _read\n    self._done()\n  File "/usr/lib64/python3.6/site-packages/whipper/program/cdparanoia.py", line 388, in _done\n    self.quality = self._parser.getTrackQuality()\n  File "/usr
/lib64/python3.6/site-packages/whipper/program/cdparanoia.py", line 199, in getTrackQuality\n    raise RuntimeError("cdparanoia couldn\'t read any frames "\nRuntimeError: cdparanoia couldn\'t read any frames for
 the current track\n')
WARNING:whipper.command.offset:cannot rip with offset 667...
ERROR:whipper.command.offset:no matching offset found. Consider trying again with a different disc
```
Gentoo also allows switching between different binary implementations of cdparanoia using ```eselect ``` and its cdparanoia plugin. Both ```cdparanoia-paranoia``` and ```libcdio-paranoia``` have the same issue.

**Comment by jwflory** [comment]
I have the same issue. I can reproduce with Whipper 0.9.0 with the Fedora 31 package when I run `whipper offset find`. It fills my `stdout` with the same error. My CD/DVD drive might not be in great physical condition, so that could be a test factor in reproducing this.

**Comment by JoeLametta** [comment]
@Viktini and probably @jwflory Your comment seems to be about a different issue (probably a manifestation of #234, known upstream bug caused by using an offset in cd-paranoia > 587).

**Comment by PongoPygmaeus** [comment]
What drives are people using?

I've gotten the "file size 0 did not match expected size" error, but only on my ASUS BW-16D1HT, and only with a couple disks in a specific box set.

**Comment by Bujiraso** [comment]
I'm seeing this with an ASUS BW-16D1HT and a TSSTcorp CDDVDW SH-S203N on only the final track of "Antichrist Superstar".
It only happens on that disc (maybe one other) of multiple hundreds so far.
The drives are both good -- cache defeated, and offset analyzed.

**Comment by JoeLametta** [comment]
@Bujiraso Hi, which are you using: `cdparanoia` (Xiph's one) or `cd-paranoia` (libcdio's one)? Does ripping the last track succeed with both programs? If the CD you're trying to rip has 99 tracks and you're using `cd-paranoia`, then you're probably experiencing issue #302 (upstream bug).

**Comment by Bujiraso** [comment]
Hey @JoeLametta , thanks for the explanation as to why I have two of them - I was wondering that!

According to https://archlinux.org/packages/extra/x86_64/cdparanoia/ I'm using the Xiph cdparanoia, but I do have both installed. 

When I run libcdio's cd-paranoia on the same disc, I get the following
```
$ cd-paranoia --stderr-progress --sample-offset=6 --force-cdrom-device /dev/sr0 -B 99 $HOME/track_99.wav
Sending all callback output to stderr for wrapper script
cdparanoia III release 10.2 libcdio 2.1.0 x86_64-pc-linux-gnu
(C) 2001 Monty <monty@xiph.org> and Xiphophorus
(C) 2004, 2005, 2008 Rocky Bernstein <rocky@gnu.org>
(C) 2014 Robert Kausch <robert.kausch@freac.org>

Report bugs to bug-libcdio@gnu.org

Selected span contains non audio track at track 101.  Aborting.

```
dBpoweramp got an accurate rip off of it, so I think the medium itself is intact.

It doesn't look to me like this is a case of #302, unless whipper is using cd-paranoia under the hood. What does whipper do when provided with both options?

**Comment by JoeLametta** [comment]
> It doesn't look to me like this is a case of #302, unless whipper is using cd-paranoia under the hood. What does whipper do when provided with both options?

Whipper uses `cd-paranoia` (libcdio's one) since [v.0.6.0](https://github.com/whipper-team/whipper/releases/tag/v0.6.0) and so do Archlinux's packages ([whipper](https://archlinux.org/packages/community/x86_64/whipper/) and AUR's [whipper-git](https://aur.archlinux.org/packages/whipper-git)). As it's a known bug, whipper-git should issue a warning about this situation. See commit: 07bd0348f30a8f929df8dba777ba5072dbc15e16.

**Comment by brainchild0** [comment]
I am affected by this issue too since running whipper  0.10.0 on first use, with command `offset find`, in a Docker container under Mint 20.1. I earlier had used a native installation of `cdparanoia` through `abcde` without any warnings.

Optical drive is [Pioneer  BDR-XD07UHD](https://www.amazon.com/gp/product/B081R7HGV4) USB device.

**Comment by eharris** [comment]
I'm having this issue as well, on a PIONEER BDR-209D, which should use offset 667.
I have both `cd-paranoia` (using libcdio) and `cdparanoia` (Xiph) installed on my system (Debian Bullseye), and was able to workaround this problem of not being able to rip at all by changing the `cdparanoia.py` script to use `cdparanoia`.

What's strange is both `cd-paranoia` and  `cdparanoia` were able to rip just fine if I used the options `-B -d /dev/sr0 -O 667` with a track number, and the resulting wav files compared as identical.  So I'm not sure why `whipper` is having trouble using `cd-paranoia` and throwing exceptions.

**Comment by dseomn** [comment]
I just got this while trying to rip an enhanced CD. Do the rest of you getting this error see it on CDs with data tracks/sessions, or regular CD-DA-only CDs? Ripping seemed to work fine the first time or two, but then it failed with this error another time. Then I ejected the disc, tried again, and it worked. (I was ripping the same CD multiple times to test changes to the script that I use to call whipper.) Here's some potentially relevant parts of `cd-info`'s output:

```
Vendor                      : HL-DT-ST
Model                       : BD-RE  WH16NS40 
Revision                    : 1.05
...
Disc mode is listed as: CD-DA
CD-ROM Track List (1 - 11)
  #: MSF       LSN    Type   Green? Copy? Channels Premphasis?
  1: 00:02:00  000000 audio  false  no    2        no
  2: 04:09:20  018545 audio  false  no    2        no
  3: 08:53:32  039857 audio  false  no    2        no
  4: 12:54:00  057900 audio  false  no    2        no
  5: 16:58:45  076245 audio  false  no    2        no
  6: 20:45:25  093250 audio  false  no    2        no
  7: 25:33:07  114832 audio  false  no    2        no
  8: 30:03:37  135112 audio  false  no    2        no
  9: 35:05:72  157797 audio  false  no    2        no
 10: 38:47:05  174380 audio  false  no    2        no
 11: 43:51:23  197198 data   false  no   
170: 71:10:45  320145 leadout (718 MB raw, 718 MB formatted)
Media Catalog Number (MCN): 0000000000000
Last CD Session LSN: 197198
audio status: invalid
__________________________________
CD Analysis Report
No CD-TEXT on Disc.
CD-Plus/Extra   
session #2 starts at track 11, LSN: 197198, ISO 9660 blocks: 319693
ISO 9660: 319693 blocks, label `SURFACING_ECD                   '
```
