### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by ghcatt** [whipper-team/whipper#475]
arch linux kde here, whipper 0.9.0-1

config file, see https://github.com/whipper-team/whipper/issues/472

```
$ whipper cd rip
Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.9.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python3.8/site-packages/whipper/command/main.py", line 42, in main
    cmd = Whipper(sys.argv[1:], os.path.basename(sys.argv[0]), None)
  File "/usr/lib/python3.8/site-packages/whipper/command/basecommand.py", line 114, in __init__
    self.cmd = self.subcommands[self.options.remainder[0]](
  File "/usr/lib/python3.8/site-packages/whipper/command/basecommand.py", line 114, in __init__
    self.cmd = self.subcommands[self.options.remainder[0]](
  File "/usr/lib/python3.8/site-packages/whipper/command/basecommand.py", line 60, in __init__
    self.add_arguments()
  File "/usr/lib/python3.8/site-packages/whipper/command/cd.py", line 241, in add_arguments
    default_offset = config.Config().getReadOffset(*info)
  File "/usr/lib/python3.8/site-packages/whipper/common/config.py", line 103, in getReadOffset
    return int(self._parser.get(section, 'read_offset'))
ValueError: invalid literal for int() with base 10: '6\t\t\t; drive read offset in positive/negative frames (no leading +)'
```

hp drive offset definitely is +6

**Comment by lonemadmax** [comment]
The error says it's trying to convert to an integer the string `6    ; drive read offset in positive/negative frames (no leading +)`, which certainly is not an integer.

From the comments in #472 it seems you don't have the unreleased fix https://github.com/whipper-team/whipper/commit/dca9fcb7dc521a2c7369c613e52e36fc7fa65e67. I'd remove inline comments from the config file and try again.

**Comment by ghcatt** [comment]
working fine now, thanks for your help.

**Comment by JoeLametta** [comment]
Related to #461.
