### ISSUE TITLE
Better error handling for unconfigured drive offset

### ISSUE THREAD

**Issue by jwflory** [whipper-team/whipper#478]
# Summary

Add less verbose and clear error handling when `whipper cd` is run without a drive offset configured

# Background

When I first used `whipper`, I didn't realize I needed the drive offset first. There is a large, mostly unhelpful stacktrace where the `ValueError` is raised. Suppressing the `stdout` to a single-line error would be a small quality-of-life enhancement for my logging.

# Details

Reproduced the first time I ran `whipper`:

```sh
whipper cd -d /dev/sr1 rip
```

```python
Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.9.0', 'console_scripts', 'whipper')()
  File "/usr/lib64/python3.7/site-packages/whipper/command/main.py", line 42, in main
    cmd = Whipper(sys.argv[1:], os.path.basename(sys.argv[0]), None)
  File "/usr/lib64/python3.7/site-packages/whipper/command/basecommand.py", line 117, in __init__
    self.options
  File "/usr/lib64/python3.7/site-packages/whipper/command/basecommand.py", line 117, in __init__
    self.options
  File "/usr/lib64/python3.7/site-packages/whipper/command/basecommand.py", line 104, in __init__
    self.handle_arguments()
  File "/usr/lib64/python3.7/site-packages/whipper/command/cd.py", line 304, in handle_arguments
    raise ValueError("Drive offset is unconfigured.\n"
ValueError: Drive offset is unconfigured.
Please install pycdio and run 'whipper offset find' to detect your drive's offset or set it manually in the configuration file. It can also be specified at runtime using the '--offset=value' argument
```

Just the last line is helpful for me as an end-user.

# Outcome

- Easier to read and understand error logs
- Produces more readable, less verbose system logs

**Comment by jwflory** [comment]
Thanks for fixing this! :rose:
