### ISSUE TITLE
IOError: [Errno 13] Permission denied: '/proc/mounts'

### ISSUE THREAD

**Issue by jonasgit** [whipper-team/whipper#501]
$ whipper offset find
INFO:whipper.command.offset:checking device /dev/sr0
WARNING:whipper.program.utils:command 'eject -t /dev/sr0' returned with exit code '1' (unable to open /etc/mtab: Permission denied)
Traceback (most recent call last):
  File "/snap/whipper/23/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.8.0', 'console_scripts', 'whipper')()
  File "/snap/whipper/23/lib/python2.7/site-packages/whipper/command/main.py", line 43, in main
    ret = cmd.do()
  File "/snap/whipper/23/lib/python2.7/site-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/snap/whipper/23/lib/python2.7/site-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/snap/whipper/23/lib/python2.7/site-packages/whipper/command/offset.py", line 84, in do
    utils.unmount_device(device)
  File "/snap/whipper/23/lib/python2.7/site-packages/whipper/program/utils.py", line 44, in unmount_device
    proc = open('/proc/mounts').read()
IOError: [Errno 13] Permission denied: '/proc/mounts'

/proc/mounts is a soft link to self/mounts. Is that a problem?
whipper installed by snap --beta.

$ whipper --version
whipper 0.8.0

Ubuntu 18.04.4 LTS

**Comment by jonasgit** [comment]
$ WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper offset find
Traceback (most recent call last):
  File "/snap/whipper/23/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.8.0', 'console_scripts', 'whipper')()
  File "/snap/whipper/23/lib/python2.7/site-packages/whipper/command/main.py", line 43, in main
    ret = cmd.do()
  File "/snap/whipper/23/lib/python2.7/site-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/snap/whipper/23/lib/python2.7/site-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/snap/whipper/23/lib/python2.7/site-packages/whipper/command/offset.py", line 84, in do
    utils.unmount_device(device)
  File "/snap/whipper/23/lib/python2.7/site-packages/whipper/program/utils.py", line 44, in unmount_device
    proc = open('/proc/mounts').read()
IOError: [Errno 13] Permission denied: '/proc/mounts'

[whipper.log.gz](https://github.com/whipper-team/whipper/files/4971741/whipper.log.gz)

**Comment by PongoPygmaeus** [comment]
What are the permissions on /etc/mtab , /proc/mounts, /proc/self/mounts?

**Comment by jonasgit** [comment]
$ ls -l  /etc/mtab /proc/mounts /proc/self/mounts
lrwxrwxrwx 1 root  root  19 Aug  3  2016 /etc/mtab -> ../proc/self/mounts
lrwxrwxrwx 1 root  root  11 Jul 25 10:36 /proc/mounts -> self/mounts
-r--r--r-- 1 jonas jonas  0 Jul 25 10:36 /proc/self/mounts

**Comment by JoeLametta** [comment]
Hi, whipper's snap package is unofficial and outdated. This seems to be an issue with the package itself...
