### ISSUE TITLE
KeyError when processing cue file

### ISSUE THREAD

**Issue by bluggy** [whipper-team/whipper#508]
It appears for some reason that the name of the 1st track is not accurately written to the que file and instead "../../data.wav" is put in there instead.  Thus when processing the cue file it is not able to locate this file and will end up generating a KeyError exception.

```shell
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.9.1.dev77+gb3aae5f', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev77+gb3aae5f-py3.7-linux-x86_64.egg/whipper/command/main.py", line 56, in main
    ret = cmd.do()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev77+gb3aae5f-py3.7-linux-x86_64.egg/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev77+gb3aae5f-py3.7-linux-x86_64.egg/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev77+gb3aae5f-py3.7-linux-x86_64.egg/whipper/command/cd.py", line 191, in do
    self.doCommand()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev77+gb3aae5f-py3.7-linux-x86_64.egg/whipper/command/cd.py", line 538, in doCommand
    self.program.verifyImage(self.runner, self.itable)
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev77+gb3aae5f-py3.7-linux-x86_64.egg/whipper/common/program.py", line 643, in verifyImage
    verifytask = image.ImageVerifyTask(cueImage)
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev77+gb3aae5f-py3.7-linux-x86_64.egg/whipper/image/image.py", line 150, in __init__
    path = image.getRealPath(index.path)
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev77+gb3aae5f-py3.7-linux-x86_64.egg/whipper/image/image.py", line 70, in getRealPath
    return self.cue.getRealPath(path)
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev77+gb3aae5f-py3.7-linux-x86_64.egg/whipper/image/cue.py", line 188, in getRealPath
    return common.getRealPath(self._path, path)
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev77+gb3aae5f-py3.7-linux-x86_64.egg/whipper/common/common.py", line 252, in getRealPath
    raise KeyError("Cannot find file for %r" % filePath)
KeyError: "Cannot find file for '../../data.wav'"
```
[whipper.log.gz](https://github.com/whipper-team/whipper/files/5242803/whipper.log.gz)

**Comment by JoeLametta** [comment]
Hi, could you also attach the toc file and the cue sheet?

**Comment by bluggy** [comment]
> Hi, could you also attach the toc file and the cue sheet?

No problem.  Both are now attached.

[whipper.cue.gz](https://github.com/whipper-team/whipper/files/5245534/whipper.cue.gz)
[whipper.toc.gz](https://github.com/whipper-team/whipper/files/5245535/whipper.toc.gz)

**Comment by JoeLametta** [comment]
Thanks, and what's the command line you run whipper with?

**Comment by bluggy** [comment]
I used the Docker `dev` image.  My Docker `whipper` alias is as follows:
```shell
docker run -ti --rm --device=/dev/sr0 --device=/dev/sr1 --device=/dev/sr2 --mount type=bind,source=${HOME}/.config/whipper,target=/home/worker/.config/whipper --mount type=bind,source=${HOME}/Music,target=/output --env WHIPPER_DEBUG=DEBUG --env WHIPPER_LOGFILE=whipper.log whipperteam/whipper:dev
```
And the `whipper` command was:
```shell
whipper cd --device /dev/sr1 rip
```

**Comment by JoeLametta** [comment]
This bug is caused by a regression introduced in commit 3acc3ffed67b83cc9e1f1b6ae42283840c92a488. I already have a fix ready which I'll probably commit tomorrow.

**Comment by JoeLametta** [comment]
The regression has been fixed with commit b754b2b0bf30a72304d1103e64d17e94ec3b36a4.

**Comment by bluggy** [comment]
Hi @JoeLametta, I just grabbed the latest `dev` Docker image which appeared to have b754b2b in it (according to the version information), but it is still exhibiting the same behavior.
```shell
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.9.1.dev85+gb754b2b', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev85+gb754b2b-py3.7-linux-x86_64.egg/whipper/command/main.py", line 56, in main
    ret = cmd.do()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev85+gb754b2b-py3.7-linux-x86_64.egg/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev85+gb754b2b-py3.7-linux-x86_64.egg/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev85+gb754b2b-py3.7-linux-x86_64.egg/whipper/command/cd.py", line 191, in do
    self.doCommand()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev85+gb754b2b-py3.7-linux-x86_64.egg/whipper/command/cd.py", line 536, in doCommand
    self.program.verifyImage(self.runner, self.itable)
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev85+gb754b2b-py3.7-linux-x86_64.egg/whipper/common/program.py", line 617, in verifyImage
    verifytask = image.ImageVerifyTask(cueImage)
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev85+gb754b2b-py3.7-linux-x86_64.egg/whipper/image/image.py", line 150, in __init__
    path = image.getRealPath(index.path)
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev85+gb754b2b-py3.7-linux-x86_64.egg/whipper/image/image.py", line 70, in getRealPath
    return self.cue.getRealPath(path)
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev85+gb754b2b-py3.7-linux-x86_64.egg/whipper/image/cue.py", line 188, in getRealPath
    return common.getRealPath(self._path, path)
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.9.1.dev85+gb754b2b-py3.7-linux-x86_64.egg/whipper/common/common.py", line 252, in getRealPath
    raise KeyError("Cannot find file for %r" % filePath)
KeyError: "Cannot find file for '../../data.wav'"
```
I've attached the cue sheet and toc file for this attempt.  Let me know if you also need me to capture the debug log again.

[whipper.cue.gz](https://github.com/whipper-team/whipper/files/5252008/whipper.cue.gz)
[whipper.toc.gz](https://github.com/whipper-team/whipper/files/5252009/whipper.toc.gz)

**Comment by JoeLametta** [comment]
JoeLametta:
> This bug is caused by a regression introduced in commit [3acc3ff](https://github.com/whipper-team/whipper/commit/3acc3ffed67b83cc9e1f1b6ae42283840c92a488). I already have a fix ready which I'll probably commit tomorrow.
> [...]
> The regression has been fixed with commit [b754b2b](https://github.com/whipper-team/whipper/commit/b754b2b0bf30a72304d1103e64d17e94ec3b36a4).

bluggy:
> Hi @JoeLametta, I just grabbed the latest `dev` Docker image which appeared to have [b754b2b](https://github.com/whipper-team/whipper/commit/b754b2b0bf30a72304d1103e64d17e94ec3b36a4) in it (according to the version information), but it is still exhibiting the same behavior.

Sorry, my bad: I got confused and marked the solution to another issue as relevant to this one. The fix mentioned in the quoted messages is related to the issue reported below:

https://github.com/whipper-team/whipper/issues/145#issuecomment-695016228
https://github.com/whipper-team/whipper/issues/145#issuecomment-695017861

@bluggy First of all I'm reopening this issue, unfortunately I still need to understand the underlying bug which is causing it...

**Comment by bluggy** [comment]
No problem, just got excited. :smile:

**Comment by jmechnich** [comment]
Funnily enough, I ran into the same issue with the same CD :rofl: 

Is there any news on this?

The problem seems to be caused by the path written for Track 1 which is preceded by a hidden track.
Here the output from the rip:

```INFO:whipper.command.cd:found Hidden Track One Audio from frame 0 to 32
INFO:whipper.command.cd:ripping track 0 of 12: 00. Various Artists - Hidden Track One Audio.flac
INFO:whipper.program.cdparanoia:checksums match, 3d7d2ab2
INFO:whipper.command.cd:CRCs match for track 0
Peak level: 0.000000
Rip quality: 100.00%
INFO:whipper.command.cd:HTOA discarded, contains digital silence
INFO:whipper.command.cd:ripping track 1 of 12: 01. Nirvana - I Hate Myself and I Want to Die.flac
INFO:whipper.program.cdparanoia:checksums match, 7e24bff8
INFO:whipper.command.cd:CRCs match for track 1
Peak level: 0.981232
Rip quality: 100.00%
```

I am very happy to help in debugging this issue...

Edit: attached [whipper.log.gz](https://github.com/whipper-team/whipper/files/7523300/whipper.log.gz) (with `WHIPPER_DEBUG=DEBUG` set)

**Comment by BBaoVanC** [comment]
Related: #582

**Comment by b-buyman** [comment]
I also found a CD with this issue:

```
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr0
CDDB disc id: 4d101006
MusicBrainz disc id 93N.4txzwHflM.wQK.5b8DqaD5Q-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+6+308583+183+44973+65255+96890+157908+230058&tracks=6&id=93N.4txzwHflM.wQK.5b8DqaD5Q-
Disc duration: 01:08:32.000, 6 audio tracks
```

There is also a hidden track 0 with digitial silence:
```
INFO:whipper.command.cd:found Hidden Track One Audio from frame 0 to 32
INFO:whipper.command.cd:ripping track 0 of 6: 00 - Hidden Track One Audio.flac
INFO:whipper.program.cdparanoia:checksums match, 3d7d2ab2
INFO:whipper.command.cd:CRCs match for track 0
Peak level: 0.000000
Rip quality: 100.00%
INFO:whipper.command.cd:HTOA discarded, contains digital silence
```

Which leads then to the know error when creating the cue sheet. 

```
Traceback (most recent call last):
  File "/usr/bin/whipper", line 33, in <module>
    sys.exit(load_entry_point('whipper==0.10.0', 'console_scripts', 'whipper')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/whipper/command/main.py", line 56, in main
    ret = cmd.do()
          ^^^^^^^^
  File "/usr/lib/python3.12/site-packages/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/whipper/command/cd.py", line 203, in do
    ret = self.doCommand()
          ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/whipper/command/cd.py", line 583, in doCommand
    self.program.verifyImage(self.runner, self.itable)
  File "/usr/lib/python3.12/site-packages/whipper/common/program.py", line 642, in verifyImage
    verifytask = image.ImageVerifyTask(cueImage)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/whipper/image/image.py", line 151, in __init__
    path = image.getRealPath(index.path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/whipper/image/image.py", line 70, in getRealPath
    return self.cue.getRealPath(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/whipper/image/cue.py", line 188, in getRealPath
    return common.getRealPath(self._path, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/whipper/common/common.py", line 252, in getRealPath
    raise KeyError("Cannot find file for %r" % filePath)
KeyError: "Cannot find file for '../../../../../../../data.wav'"
```

I can provide more info if helpful, I might try to dig into the codebase myself when I have an overview and know where to start.

**Comment by BBaoVanC** [comment]
> There is also a hidden track 0 with digitial silence:

Just FYI, this isn't really special; all it means is there is a margin before track 1 on the beginning of the disc, which almost every CD has.

The issue isn't really happening anywhere in that stack trace unfortunately, since that's just showing the verification step where it tries to parse the CUE to make sure it's valid. Somehow the FILE parameter is being set to `./../../../../../../data.wav` during ripping.

I don't have time to investigate further but with that amount of `../` there is clearly some accidentally infinite loop where it walks up the filesystem to root.

**Comment by b-buyman** [comment]
> Just FYI, this isn't really special; all it means is there is a margin before track 1 on the beginning of the disc, which almost every CD has.

OK, thank you for the clarification. Still wondering if it is linked to this issue though. 

> The issue isn't really happening anywhere in that stack trace unfortunately, since that's just showing the verification step where it tries to parse the CUE to make sure it's valid. Somehow the FILE parameter is being set to `./../../../../../../data.wav` during ripping.

I'm not sure if that's exactly what is happening here. The function used is `getRelativePath` from https://github.com/whipper-team/whipper/blob/develop/whipper/common/common.py, but it seems to work as intended. It tries to get the path difference between `data.wav` and the target folder, and for `data.wav` it assumes to be in the root folder without the full file path:

```
DEBUG:whipper.common.common:getRelativePath: target 'data.wav', collection '/home/andreas/Music/Compilation/Various Artists/2009 - 111 Years of Deutsche Grammophon: The Collectors’ Edition/Disc 8 of 55 - Boulez - Stravinsky/Various Artists - 111 Years of Deutsche Grammophon: The Collectors’ Edition (Disc 8 of 55): Boulez - Stravinsky.cue'
DEBUG:whipper.common.common:getRelativePath: target and collection in different dir, '../../../../../../..'
```

In comparison another disc of the set:

```
DEBUG:whipper.common.common:getRelativePath: target '/home/andreas/Music/Compilation/Various Artists/2009 - 111 Years of Deutsche Grammophon: The Collectors’ Edition/Disc 1 of 55 - Abbado - Brahms - Hungarian Dances/01 - Hungarian Dance no. 1 in G minor: Allegro molto.flac', collection '/home/andreas/Music/Compilation/Various Artists/2009 - 111 Years of Deutsche Grammophon: The Collectors’ Edition/Disc 1 of 55 - Abbado - Brahms - Hungarian Dances/Various Artists - 111 Years of Deutsche Grammophon: The Collectors’ Edition (Disc 1 of 55): Abbado - Brahms - Hungarian Dances.cue'
DEBUG:whipper.common.common:getRelativePath: target and collection in same dir
```

So I assume calling the function for `data.wav` is wrong in the first place, but I haven't found the underlying issue yet. Hidden track with silence is handled the same way in both logs:

```
DEBUG:whipper.command.cd:HTOA peak 0 is equal to the SILENT threshold, disregarding
DEBUG:whipper.image.table:setFile: track 1, index 0, path None, length 33, counter 0
DEBUG:whipper.image.table:setting path None, relative 0 on track 1, index 0, counter 0
DEBUG:whipper.command.cd:unlinking '/home/andreas/Music/Compilation/Various Artists/2009 - 111 Years of Deutsche Grammophon: The Collectors’ Edition/Disc 8 of 55 - Boulez - Stravinsky/00 - Hidden Track One Audio.flac'
INFO:whipper.command.cd:HTOA discarded, contains digital silence
```

And for working disc 1
```
DEBUG:whipper.command.cd:HTOA peak 0 is equal to the SILENT threshold, disregarding
DEBUG:whipper.image.table:setFile: track 1, index 0, path None, length 32, counter 0
DEBUG:whipper.image.table:setting path None, relative 0 on track 1, index 0, counter 0
DEBUG:whipper.command.cd:unlinking '/home/andreas/Music/Compilation/Various Artists/2009 - 111 Years of Deutsche Grammophon: The Collectors’ Edition/Disc 1 of 55 - Abbado - Brahms - Hungarian Dances/00 - Hidden Track One Audio.flac'
INFO:whipper.command.cd:HTOA discarded, contains digital silence
```

Next step will be to analyze the functions for cue generation. 

I attached two logs from two different disks of the collection. whipper.log.gz containing the log of disc 8 with the error, whipper2.log.gz was the log of disc 1 without the error. 

Edit: Yes, this seems to be the right path. Cue file is generated wrong for track 1. Instead of `FILE "01 - Pétrouchka (1911): First Tableau.flac" WAVE` it uses the temporary `data.wav` in the table:

```
REM DISCID 4D101006
REM COMMENT "whipper 0.10.0"
CATALOG 0028947783862
FILE "../../../../../../../data.wav" WAVE
  TRACK 01 AUDIO
    ISRC DEF059102811
    PREGAP 00:00:33
    INDEX 01 00:00:00
    INDEX 02 05:30:17
    INDEX 03 07:21:42
FILE "02 - Pétrouchka (1911): Second Tableau.flac" WAVE
  TRACK 02 AUDIO
    ISRC DEF059102812
    INDEX 01 00:00:00
```

I'll dig deeper later.

**Comment by sethkush** [comment]
Hi, I'm running into the same issue with the following release:

```
CDDB disc id: b309af10
MusicBrainz disc id mwlFpebNkBpjpXSxIsZXfQBV4Io-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+16+186145+183+4710+12715+16673+19058+46580+62025+68405+83233+92520+97683+108763+117593+144403+155678+162923&tracks=16&id=mwlFpebNkBpjpXSxIsZXfQBV4Io-
Disc duration: 00:41:19.493, 16 audio tracks
```

Here's the traceback:
```
Traceback (most recent call last):
  File "/usr/bin/whipper", line 33, in <module>
    sys.exit(load_entry_point('whipper==0.10.1.dev36+gbc8b96d', 'console_scripts', 'whipper')())
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/whipper/command/main.py", line 56, in main
    ret = cmd.do()
  File "/usr/lib/python3.13/site-packages/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
           ~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
           ~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/whipper/command/cd.py", line 203, in do
    ret = self.doCommand()
  File "/usr/lib/python3.13/site-packages/whipper/command/cd.py", line 582, in doCommand
    self.program.verifyImage(self.runner, self.itable)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/whipper/common/program.py", line 649, in verifyImage
    verifytask = image.ImageVerifyTask(cueImage)
  File "/usr/lib/python3.13/site-packages/whipper/image/image.py", line 153, in __init__
    path = image.getRealPath(index.path)
  File "/usr/lib/python3.13/site-packages/whipper/image/image.py", line 70, in getRealPath
    return self.cue.getRealPath(path)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/site-packages/whipper/image/cue.py", line 188, in getRealPath
    return common.getRealPath(self._path, path)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/whipper/common/common.py", line 252, in getRealPath
    raise KeyError("Cannot find file for %r" % filePath)
KeyError: "Cannot find file for '../../../../../../data.wav'"
```

[Johann Sebastian Bach; John Eliot Gardiner, The Monteverdi Choir, The London Oratory Junior Choir, The English Baroque Soloists - St. Matthew Passion (Disc 3 of 3).toc.gz](https://github.com/user-attachments/files/21723573/Johann.Sebastian.Bach.John.Eliot.Gardiner.The.Monteverdi.Choir.The.London.Oratory.Junior.Choir.The.English.Baroque.Soloists.-.St.Matthew.Passion.Disc.3.of.3.toc.gz)
[Johann Sebastian Bach; John Eliot Gardiner, The Monteverdi Choir, The London Oratory Junior Choir, The English Baroque Soloists - St. Matthew Passion (Disc 3 of 3).cue.gz](https://github.com/user-attachments/files/21723574/Johann.Sebastian.Bach.John.Eliot.Gardiner.The.Monteverdi.Choir.The.London.Oratory.Junior.Choir.The.English.Baroque.Soloists.-.St.Matthew.Passion.Disc.3.of.3.cue.gz)

**Comment by whiteawake** [comment]
I am also encountering this issue, with the following release:

```
CDDB disc id: 020dce01
MusicBrainz disc id 6V6GoqXydpKv7e86wsvtuXevYyE-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+1+265267+182&tracks=1&id=6V6GoqXydpKv7e86wsvtuXevYyE-
Disc duration: 00:58:54.466, 1 audio tracks
```

The traceback:

```python
Traceback (most recent call last):
  File "/usr/bin/whipper", line 33, in <module>
    sys.exit(load_entry_point('whipper==0.10.0', 'console_scripts', 'whipper')())
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/whipper/command/main.py", line 56, in main
    ret = cmd.do()
  File "/usr/lib/python3.13/site-packages/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
           ~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
           ~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/whipper/command/cd.py", line 203, in do
    ret = self.doCommand()
  File "/usr/lib/python3.13/site-packages/whipper/command/cd.py", line 583, in doCommand
    self.program.verifyImage(self.runner, self.itable)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/whipper/common/program.py", line 642, in verifyImage
    verifytask = image.ImageVerifyTask(cueImage)
  File "/usr/lib/python3.13/site-packages/whipper/image/image.py", line 151, in __init__
    path = image.getRealPath(index.path)
  File "/usr/lib/python3.13/site-packages/whipper/image/image.py", line 70, in getRealPath
    return self.cue.getRealPath(path)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/site-packages/whipper/image/cue.py", line 188, in getRealPath
    return common.getRealPath(self._path, path)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/whipper/common/common.py", line 252, in getRealPath
    raise KeyError("Cannot find file for %r" % filePath)
KeyError: "Cannot find file for '../../../../../../data.wav'"
```

Using the command:

```bash
whipper cd -d /dev/sr1 rip -p -C complete -k
```

**Comment by dseomn** [comment]
https://github.com/whipper-team/whipper/issues/508#issuecomment-694845046 has non-default `INDEX`es in track 1:

```
// Track 1
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
SILENCE 00:00:37
FILE "data.wav" 0 04:02:60
START 00:00:37
INDEX 01:11:49
INDEX 03:53:49
```

https://github.com/whipper-team/whipper/issues/508#issuecomment-2453376666 too:

```
FILE "../../../../../../../data.wav" WAVE
  TRACK 01 AUDIO
    ISRC DEF059102811
    PREGAP 00:00:33
    INDEX 01 00:00:00
    INDEX 02 05:30:17
    INDEX 03 07:21:42
```

One of my CDs with this bug too:

```
// Track 1
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230801"
SILENCE 00:00:33
FILE "data.wav" 0 05:34:47
START 00:00:33
INDEX 01:58:10
```

Given that additional indexes are relatively rare, any chance that this bug is triggered if and only if track 1 has more than 1 index?

**Comment by dseomn** [comment]
> Given that additional indexes are relatively rare, any chance that this bug is triggered if and only if track 1 has more than 1 index?

Nope, that was at least partially wrong.

This CD with multiple indexes in track 1 ripped fine:

```
CD_DA


// Track 1
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
FILE "data.wav" 0 04:48:27
INDEX 00:13:17
INDEX 04:16:05


// Track 2
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
FILE "data.wav" 04:48:27 03:03:25
START 00:04:38


// Track 3
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
FILE "data.wav" 07:51:52 02:15:58
START 00:03:18


// Track 4
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
FILE "data.wav" 10:07:35 11:38:42
START 00:03:22


// Track 5
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
FILE "data.wav" 21:46:02 01:20:08
START 00:02:08


// Track 6
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
FILE "data.wav" 23:06:10 06:47:42
START 00:00:47


// Track 7
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
FILE "data.wav" 29:53:52 02:34:00
START 00:02:35


// Track 8
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
FILE "data.wav" 32:27:52 08:30:15
START 00:02:50


// Track 9
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
FILE "data.wav" 40:57:67 08:21:05
START 00:02:13

```

But this one had this `KeyError` bug:

```
CD_DA

CATALOG "0028941427526"

// Track 1
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230801"
SILENCE 00:00:33
FILE "data.wav" 0 05:34:47
START 00:00:33
INDEX 01:58:10


// Track 2
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230803"
FILE "data.wav" 05:34:47 07:03:25
INDEX 02:23:10


// Track 3
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230805"
FILE "data.wav" 12:37:72 04:59:00


// Track 4
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230806"
FILE "data.wav" 17:36:72 01:39:25


// Track 5
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230807"
FILE "data.wav" 19:16:22 06:14:48
INDEX 04:02:55


// Track 6
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230809"
FILE "data.wav" 25:30:70 02:39:62


// Track 7
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230810"
FILE "data.wav" 28:10:57 05:03:15
INDEX 02:17:73


// Track 8
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230812"
FILE "data.wav" 33:13:72 03:31:50
START 00:14:15


// Track 9
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230813"
FILE "data.wav" 36:45:47 03:41:70


// Track 10
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230814"
FILE "data.wav" 40:27:42 05:33:10
INDEX 02:34:73


// Track 11
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230816"
FILE "data.wav" 46:00:52 01:00:45


// Track 12
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230817"
FILE "data.wav" 47:01:22 03:27:13


// Track 13
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230818"
FILE "data.wav" 50:28:35 04:02:50


// Track 14
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBF077230819"
FILE "data.wav" 54:31:10 01:48:17

```

Maybe it's triggered by multiple indexes and `SILENCE` or `START` in track 1?
