### ISSUE TITLE
no CD detected, please insert one and retry

### ISSUE THREAD

**Issue by bydioeds** [whipper-team/whipper#511]
Hi, i'm having an error when i tried `whipper cd rip` and `whipper cd info` 

here are the logs
```
INFO:whipper.command.cd:checking device /dev/sr0
WARNING:whipper.program.utils:command 'eject -t /dev/sr0' returned with exit code '1' (b'eject: CD-ROM tray close command failed: Error de entrada/salida')
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 33, in <module>
    sys.exit(load_entry_point('whipper==0.9.1.dev99+gd885e79', 'console_scripts', 'whipper')())
  File "/usr/local/lib/python3.8/dist-packages/whipper-0.9.1.dev99+gd885e79-py3.8-linux-i686.egg/whipper/command/main.py", line 56, in main
    ret = cmd.do()
  File "/usr/local/lib/python3.8/dist-packages/whipper-0.9.1.dev99+gd885e79-py3.8-linux-i686.egg/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.8/dist-packages/whipper-0.9.1.dev99+gd885e79-py3.8-linux-i686.egg/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.8/dist-packages/whipper-0.9.1.dev99+gd885e79-py3.8-linux-i686.egg/whipper/command/cd.py", line 100, in do
    raise OSError("no CD detected, please insert one and retry")
OSError: no CD detected, please insert one and retry
```

```
DEBUG:musicbrainzngs:set user-agent to whipper/0.9.1.dev99+gd885e79 python-musicbrainzngs/0.7.1 ( https://github.com/whipper-team/whipper )
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:looking at section 'drive:TSSTcorp%3ACDRWDVD%20TSL462D%20%3ADE07'
DEBUG:whipper.common.config:vendor: 'TSSTcorp' versus 'TSSTcorp'
DEBUG:whipper.common.config:model: 'CDRWDVD TSL462D ' versus 'CDRWDVD TSL462D'
DEBUG:whipper.common.config:release: 'DE07' versus 'DE07'
INFO:whipper.command.cd:using configured read offset 6
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
DEBUG:whipper.common.config:loaded 1 sections from config file
INFO:whipper.command.cd:checking device /dev/sr0
DEBUG:whipper.program.utils:loading (eject -t) device /dev/sr0
WARNING:whipper.program.utils:command 'eject -t /dev/sr0' returned with exit code '1' (b'eject: CD-ROM tray close command failed: Error de entrada/salida')
DEBUG:whipper.program.utils:possibly unmount real path '/dev/sr0'
```
i suppose is because my cd tray just pops out instead of sliding. 
I hope i did say it clearly as you can read my english isn't that good.

Edit: 
The command `eject /dev/sr0` works fine, i suppose `eject -t /dev/sr0` doesn't because i need mannually push the cd tray

i found a workaround about it and is to change this line

https://github.com/whipper-team/whipper/blob/d885e79c9f7524c05ac15a2b7f2860304059639c/whipper/command/cd.py#L99 

 to this `if False:` 

a `--force` option is what is needed maybe?

**Comment by spvkgn** [comment]
same error, since commit 921e25bf985ae9e1f9fa3240f5de4a831b89ada0
