### ISSUE TITLE
AccurateRipResponse test failures

### ISSUE THREAD

**Issue by felixonmars** [whipper-team/whipper#515]
```
======================================================================
FAIL: test_AccurateRipResponse_parses_correctly (whipper.test.test_common_accurip.TestAccurateRipResponse)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/whipper/src/whipper-0.9.0/whipper/test/test_common_accurip.py", line 80, in test_AccurateRipResponse_parses_correctly
    self.assertEqual(responses[1].confidences[0], 6)
AssertionError: 7 != 6

======================================================================
FAIL: test_can_return_entry_without_saving (whipper.test.test_common_accurip.TestAccurateRipResponse)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/whipper/src/whipper-0.9.0/whipper/test/test_common_accurip.py", line 53, in test_can_return_entry_without_saving
    self.assertEqual(get_db_entry(self.path), self.entry)
AssertionError: Lists differ: [<whi[55 chars]2f621d3370>, <whipper.common.accurip._Accurate[33 chars]370>] != [<whi[55 chars]2f621073d0>, <whipper.common.accurip._Accurate[33 chars]700>]

First differing element 1:
<whipper.common.accurip._AccurateRipResponse object at 0x7f2f62eb3370>
<whipper.common.accurip._AccurateRipResponse object at 0x7f2f62107700>

- [<whipper.common.accurip._AccurateRipResponse object at 0x7f2f621d3370>,
?                                                                   ---

+ [<whipper.common.accurip._AccurateRipResponse object at 0x7f2f621073d0>,
?                                                                  +++

-  <whipper.common.accurip._AccurateRipResponse object at 0x7f2f62eb3370>]
?                                                                 ^^^^

+  <whipper.common.accurip._AccurateRipResponse object at 0x7f2f62107700>]
?                                                                 ^^ ++


======================================================================
FAIL: test_retrieves_and_saves_accuraterip_entry (whipper.test.test_common_accurip.TestAccurateRipResponse)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/whipper/src/whipper-0.9.0/whipper/test/test_common_accurip.py", line 60, in test_retrieves_and_saves_accuraterip_entry
    self.assertEqual(get_db_entry(self.path), self.entry)
AssertionError: Lists differ: [<whi[57 chars]62107550>, <whipper.common.accurip._AccurateRi[31 chars]580>] != [<whi[57 chars]621073d0>, <whipper.common.accurip._AccurateRi[31 chars]700>]

First differing element 1:
<whipper.common.accurip._AccurateRipResponse object at 0x7f2f621d3580>
<whipper.common.accurip._AccurateRipResponse object at 0x7f2f62107700>

- [<whipper.common.accurip._AccurateRipResponse object at 0x7f2f62107550>,
?                                                                    ^^

+ [<whipper.common.accurip._AccurateRipResponse object at 0x7f2f621073d0>,
?                                                                    ^^

-  <whipper.common.accurip._AccurateRipResponse object at 0x7f2f621d3580>]
?                                                                  ^^^^

+  <whipper.common.accurip._AccurateRipResponse object at 0x7f2f62107700>]
?                                                                  ^^^^


----------------------------------------------------------------------
Ran 110 tests in 5.658s

FAILED (failures=3)
```

**Comment by JoeLametta** [comment]
Hi, thanks for opening this issue.
For the tests we rely on live data which sometimes change generating failures like these.
These failures have been already fixed in `develop` with commit bbed92bb3070af8f85d1148970f3269a97abcdb3.

Maybe I should tag a new release...

Related to #8, #291.
