### ISSUE TITLE
whipper crashes after tracking.

### ISSUE THREAD

**Issue by lockheed** [whipper-team/whipper#516]
Whatever CD I try to rip, whipper either stops (because CD cannot be found in Accurip DB) or it crashes on a later stage, after scanning track. For example:

> $ whipper cd rip
> INFO:whipper.command.cd:using configured read offset 102
> INFO:whipper.command.cd:checking device /dev/sr0
> WARNING:whipper.program.utils:command 'eject -t /dev/sr0' returned with exit code '1' (b'eject: CD-ROM tray close command failed: Input/output error')
> CDDB disc id: fa109a11
> MusicBrainz disc id rg3Dt3UdQfTQpGkS0xkPa5XZJkI-
> MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+17+318920+150+3439+19876+36824+54498+71600+96693+125918+152787+172373+183675+203151+214774+234411+249856+270098+287688&tracks=17&id=rg3Dt3UdQfTQpGkS0xkPa5XZJkI-
> Disc duration: 01:10:50.266, 17 audio tracks
> 
> Matching releases:
> 
> Artist  : Various Artists
> Title   : Siesta 8 - Muzyka Świata & Stare Radio (Disc 1 of 2): Muzyka Świata
> Duration: 01:11:03.906
> URL     : https://musicbrainz.org/release/14d2d27e-4571-4505-bac9-1c0346c7c040
> Release : 14d2d27e-4571-4505-bac9-1c0346c7c040
> Type    : Compilation
> Barcode : 600753409374
> Country : Poland
> Cat no  : 5340937
> 
> Track 1 finished, found 699 Q sub-channels with CRC errors
> Track 2 finished, found 5528 Q sub-channels with CRC errors
> Track 3 finished, found 5863 Q sub-channels with CRC errors
> Track 4 finished, found 5917 Q sub-channels with CRC errors
> Track 5 finished, found 5628 Q sub-channels with CRC errors
> Track 6 finished, found 8094 Q sub-channels with CRC errors
> Track 7 finished, found 10135 Q sub-channels with CRC errors
> Track 8 finished, found 8929 Q sub-channels with CRC errors
> Track 9 finished, found 157 Q sub-channels with CRC errors
> Track 10 finished, found 3701 Q sub-channels with CRC errors
> Track 11 finished, found 6733 Q sub-channels with CRC errors
> Track 12 finished, found 3510 Q sub-channels with CRC errors
> Track 13 finished, found 6967 Q sub-channels with CRC errors
> Track 14 finished, found 4767 Q sub-channels with CRC errors
> Track 15 finished, found 7194 Q sub-channels with CRC errors
> Track 16 finished, found 5738 Q sub-channels with CRC errors
> Track 17 finished, found 10305 Q sub-channels with CRC errors
> Traceback (most recent call last):
>   File "/snap/whipper/25/usr/bin/whipper", line 11, in <module>
>     load_entry_point('whipper==0.9.1.dev100+g04ff005', 'console_scripts', 'whipper')()
>   File "/snap/whipper/25/usr/lib/python3/dist-packages/whipper/command/main.py", line 56, in main
>     ret = cmd.do()
>   File "/snap/whipper/25/usr/lib/python3/dist-packages/whipper/command/basecommand.py", line 141, in do
>     return self.cmd.do()
>   File "/snap/whipper/25/usr/lib/python3/dist-packages/whipper/command/basecommand.py", line 141, in do
>     return self.cmd.do()
>   File "/snap/whipper/25/usr/lib/python3/dist-packages/whipper/command/cd.py", line 155, in do
>     self.itable = self.program.getTable(self.runner,
>   File "/snap/whipper/25/usr/lib/python3/dist-packages/whipper/common/program.py", line 135, in getTable
>     itable.getMusicBrainzDiscId())
>   File "/snap/whipper/25/usr/lib/python3/dist-packages/whipper/image/table.py", line 372, in getMusicBrainzDiscId
>     disc = put(values[0], values[1], values[2], values[3:])
>   File "/snap/whipper/25/usr/lib/python3/dist-packages/discid/disc.py", line 76, in put
>     disc.put(first, last, disc_sectors, track_offsets)
>   File "/snap/whipper/25/usr/lib/python3/dist-packages/discid/disc.py", line 176, in put
>     raise TOCError(self._get_error_msg())
> discid.disc.TOCError: Disc too long
>

**Comment by JoeLametta** [comment]
Hi, could you try ripping those CDs again in whipper as explained [here](https://github.com/whipper-team/whipper#bug-reports--feature-requests)?
Could you also run the following commands on the same device (same CDs), then post the content of the generated files (`cdrdao_disk-info_CD1.log`, `cdrdao_read-toc_fast_CD1.log`, `cdrdao_read-toc_slow_CD1.log`, `cdrdao_fast_CD1.toc`, `cdrdao_slow_CD1.toc`, `cdrdao_disk-info_CD2.log`, `cdrdao_read-toc_fast_CD2.log`, `cdrdao_read-toc_slow_CD2.log`, `cdrdao_fast_CD2.toc`, `cdrdao_slow_CD2.toc`)?

For the first CD:
```bash
sudo umount /dev/sr0
cdrdao disk-info --device /dev/sr0 > cdrdao_disk-info_CD1.log 2>&1
cdrdao read-toc --device /dev/sr0 --fast-toc cdrdao_fast_CD1.toc > cdrdao_read-toc_fast_CD1.log 2>&1
cdrdao read-toc --device /dev/sr0 cdrdao_slow_CD1.toc > cdrdao_read-toc_slow_CD1.log 2>&1
```

For the other CD:
```bash
sudo umount /dev/sr0
cdrdao disk-info --device /dev/sr0 > cdrdao_disk-info_CD2.log 2>&1
cdrdao read-toc --device /dev/sr0 --fast-toc cdrdao_fast_CD2.toc > cdrdao_read-toc_fast_CD2.log 2>&1
cdrdao read-toc --device /dev/sr0 cdrdao_slow_CD2.toc > cdrdao_read-toc_slow_CD2.log 2>&1
```

BTW: which CD drive are you using?

**Comment by lockheed** [comment]
Thanks for the tips.
1. When I run 
whipper cd rip -L eac
I get 
```
$ whipper cd rip -L eac
INFO:whipper.command.cd:using configured read offset 102
CRITICAL:whipper.command.cd:No logger named eac found!
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/whipper/command/cd.py", line 317, in handle_arguments
    self.logger = result.getLoggers()[self.options.logger]()
KeyError: 'eac'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/whipper", line 33, in <module>
    sys.exit(load_entry_point('whipper==0.9.0', 'console_scripts', 'whipper')())
  File "/usr/lib/python3.9/site-packages/whipper/command/main.py", line 42, in main
    cmd = Whipper(sys.argv[1:], os.path.basename(sys.argv[0]), None)
  File "/usr/lib/python3.9/site-packages/whipper/command/basecommand.py", line 114, in __init__
    self.cmd = self.subcommands[self.options.remainder[0]](
  File "/usr/lib/python3.9/site-packages/whipper/command/basecommand.py", line 114, in __init__
    self.cmd = self.subcommands[self.options.remainder[0]](
  File "/usr/lib/python3.9/site-packages/whipper/command/basecommand.py", line 104, in __init__
    self.handle_arguments()
  File "/usr/lib/python3.9/site-packages/whipper/command/cd.py", line 321, in handle_arguments
    raise ValueError(msg)
ValueError: No logger named eac found!
```

When I run 'whipper cd rip -h' I do not see any section listing installed loggers.

2. I uploaded logs for CD1 here: https://filebin.net/snufw3iv0g3eknhc/CD1_logs.zip?t=mevu13km  (link will expire in 1 week).
I do not remember what was CD2 so let's put that one on hold.

**Comment by JoeLametta** [comment]
>     1. When I run
>        whipper cd rip -L eac
> [...]
> When I run 'whipper cd rip -h' I do not see any section listing installed loggers.

Do you need an alternative logger? Anyway that probably happens because you've not installed the eac logger plugin ([link here](https://github.com/whipper-team/whipper-plugin-eaclogger)).

Analyzing the provided files it seems that the toc file generated by cdrdao's slow read-toc pass isn't correct:

![diff](https://user-images.githubusercontent.com/11859701/103138029-8eec7300-46ce-11eb-8a86-7f473e196bab.png)

Unfortunately this looks like an upstream bug in cdrdao.
