### ISSUE TITLE
Exception when querying newly created entry in MusicBrainz database

### ISSUE THREAD

**Issue by mtdcr** [whipper-team/whipper#533]
I've seen this exception a couple of times just after having added a new Disc ID to MusicBrainz:

```
Traceback (most recent call last):
  File "[...]/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.9.1.dev110+geeba910', 'console_scripts', 'whipper')()
  File "[...]/lib/python3.8/site-packages/whipper-0.9.1.dev110+geeba910-py3.8-linux-x86_64.egg/whipper/command/main.py", line 56, in main
    ret = cmd.do()
  File "[...]/lib/python3.8/site-packages/whipper-0.9.1.dev110+geeba910-py3.8-linux-x86_64.egg/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "[...]/lib/python3.8/site-packages/whipper-0.9.1.dev110+geeba910-py3.8-linux-x86_64.egg/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "[...]/lib/python3.8/site-packages/whipper-0.9.1.dev110+geeba910-py3.8-linux-x86_64.egg/whipper/command/cd.py", line 115, in do
    self.program.getMusicBrainz(self.ittoc, self.mbdiscid,
  File "[...]/lib/python3.8/site-packages/whipper-0.9.1.dev110+geeba910-py3.8-linux-x86_64.egg/whipper/common/program.py", line 293, in getMusicBrainz
    metadatas = mbngs.musicbrainz(mbdiscid,
  File "[...]/lib/python3.8/site-packages/whipper-0.9.1.dev110+geeba910-py3.8-linux-x86_64.egg/whipper/common/mbngs.py", line 423, in musicbrainz
    logger.debug('duration %r', md.duration)
AttributeError: 'DiscMetadata' object has no attribute 'duration'
```
I have never seen it happen twice in a row. I think whipper should either catch this exception and retry a few times, waiting a few seconds between new attempts, or fail gracefully advising the user to retry later.

**Comment by JoeLametta** [comment]
Pinging @Freso on this one.

**Comment by Freso** [comment]
When adding a Disc ID the Recordings and Tracks get their lengths recalculated based on that, which I believe is handled by a database trigger. However, this means that there is sometimes a delay of up to a few minutes before these updates get calculated and stored.

> I think whipper should either catch this exception and retry a few times, waiting a few seconds between new attempts, or fail gracefully advising the user to retry later.

Seems like a sane suggestion/approach to deal with this.
