### ISSUE TITLE
Error when using mblookup

### ISSUE THREAD

**Issue by givepraise** [whipper-team/whipper#535]
Hi. I am using whipper under Ubuntu 20.10 (Version: 0.9.0-4). The following is happening when I run mblookup...
```
$ whipper mblookup mbdiscid
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/musicbrainzngs/musicbrainz.py", line 497, in _safe_read
    f = opener.open(req)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/whipper/common/mbngs.py", line 298, in musicbrainz
    result = musicbrainzngs.get_releases_by_discid(
  File "/usr/lib/python3/dist-packages/musicbrainzngs/musicbrainz.py", line 1038, in get_releases_by_discid
    return _do_mb_query("discid", id, includes, params)
  File "/usr/lib/python3/dist-packages/musicbrainzngs/musicbrainz.py", line 728, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "/usr/lib/python3/dist-packages/musicbrainzngs/musicbrainz.py", line 417, in __call__
    return self.fun(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/musicbrainzngs/musicbrainz.py", line 690, in _mb_request
    resp = _safe_read(opener, req, body)
  File "/usr/lib/python3/dist-packages/musicbrainzngs/musicbrainz.py", line 503, in _safe_read
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.0.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python3/dist-packages/whipper/command/main.py", line 43, in main
    ret = cmd.do()
  File "/usr/lib/python3/dist-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib/python3/dist-packages/whipper/command/mblookup.py", line 25, in do
    metadatas = musicbrainz(discId)
  File "/usr/lib/python3/dist-packages/whipper/common/mbngs.py", line 307, in musicbrainz
    raise MusicBrainzException(e)
whipper.common.mbngs.MusicBrainzException: caused by: HTTP Error 400: Bad Request
```
Any thoughts? Thank you.

**Comment by Freso** [comment]
"mbdiscid" is not a valid argument… That said, for me `whipper mblookup mbdiscid` just returns with nothing, and doing `whipper mblookup KnpGsLhvH.lPrNc1PBL21lb9Bg4-` actually returns info, so I can’t reproduce. What version of `musicbrainzngs` do you have installed?

**Comment by givepraise** [comment]
Oh I see. My mistake. 
```
Package: python3-musicbrainzngs
Version: 0.7.1-2
```
