### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'path'

### ISSUE THREAD

**Issue by darylf** [whipper-team/whipper#550]
I'm not sure what details I need to provide in order to help troubleshoot this. I'm trying to rip a (Delerium - Karma), and I'm getting a runtime error. I don't have any other CD-rom drives to test with, or any other ripping software to run.

I'm using whipper v0.10.0 on Fedora.

How can I help diagnose what's going on?

```
  ~ whipper cd rip
WARNING:whipper.command.main:Parameter 'use_https' is missing in versions of musicbrainzngs < 0.7. This means whipper will only be able to communicate with the configured MusicBrainz server ('musicbrainz.org') over plain HTTP. If a custom server which speaks HTTPS only has been declared, a suitable version of the musicbrainzngs module will be needed to make it work in whipper.
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr0
WARNING:whipper.program.utils:command 'eject -t /dev/sr0' returned with exit code '1' (b'eject: CD-ROM tray close command failed: Input/output error')
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/usr/lib64/python3.9/site-packages/whipper/program/cdrdao.py", line 153, in _done
    self.toc.parse()
  File "/usr/lib64/python3.9/site-packages/whipper/image/toc.py", line 243, in parse
    self._index(currentTrack, 1, absoluteOffset, pregapLength)
  File "/usr/lib64/python3.9/site-packages/whipper/image/toc.py", line 170, in _index
    currentTrack.index(i, path=s.path,
AttributeError: 'NoneType' object has no attribute 'path'
CRITICAL:whipper.command.main:exception AttributeError at /usr/lib64/python3.9/site-packages/whipper/image/toc.py:170: _index(): 'NoneType' object has no attribute 'path'
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/usr/lib64/python3.9/site-packages/whipper/program/cdrdao.py", line 153, in _done
    self.toc.parse()
  File "/usr/lib64/python3.9/site-packages/whipper/image/toc.py", line 243, in parse
    self._index(currentTrack, 1, absoluteOffset, pregapLength)
  File "/usr/lib64/python3.9/site-packages/whipper/image/toc.py", line 170, in _index
    currentTrack.index(i, path=s.path,
AttributeError: 'NoneType' object has no attribute 'path'
```

**Comment by vijfhoek** [comment]
Same issue here, on whipper v0.10.0 on Fedora as well, ripping Eagles - Hotel California.

```
DEBUG:whipper.extern.task.task:notifying progress: 1.0 on 'Reading TOC'
DEBUG:whipper.image.table:set logName
DEBUG:whipper.image.toc:found catalog number 0075590010326
DEBUG:whipper.image.toc:found track 1, mode AUDIO, at absoluteOffset 0
DEBUG:whipper.image.toc:silence of '3728:15:16'
DEBUG:whipper.image.toc:appending source, counter 0, abs offset 0, source None
DEBUG:whipper.image.toc:file data.wav, start 0, length 0
DEBUG:whipper.image.toc:track 1, switched to new file, increased counter to 1
DEBUG:whipper.image.toc:appending source, counter 1, abs offset 16777141, source <File 'data.wav'>
DEBUG:whipper.image.toc:at abs offset 0, we are in source None
DEBUG:whipper.extern.task.task:exception when calling scheduled callable <bound method ReadTOCTask._read of <whipper.program.cdrdao.ReadTOCTask object at 0x7f6b09f39c10>>
DEBUG:whipper.extern.task.task:set exception, AttributeError("'NoneType' object has no attribute 'path'"), "exception AttributeError at /usr/lib64/python3.12/site-packages/whipper/image/toc.py:170: _index(): 'NoneType' object has no attribute 'path'"
```

What was interesting to me was `DEBUG:whipper.image.toc:silence of '3728:15:16'`. That's a pretty long silence, could that perhaps be the issue? Maybe some form of copy protection?

**Comment by darylf** [comment]
That's an interesting theory. Since my issue was from three years ago, I honestly don’t remember how I resolved it—if I ever did. I likely just gave up on ripping that album. I’d like to give it another try, but I might be tied up over the holidays. If I do get a chance, I’ll report back, or hopefully, someone else can shed some light on the original concern in the meantime.

**Comment by vijfhoek** [comment]
It seems to be an issue in cdrdao:

```
> cdrdao read-toc toc
/dev/sr0: HL-DT-ST DVDRAM GH24NSD1      Rev: LG00
Using driver: Generic SCSI-3/MMC - Version 2.0 (options 0x0000)

Reading toc data...
WARNING: Could not determine if raw toc data is BCD or HEX. Please report!
WARNING: Using TOC data retrieved with generic method (no multi session support).
WARNING: Use driver option 0x80000 or 0x100000 to assume BCD or HEX data.

Track   Mode    Flags  Start                Length
------------------------------------------------------------
 1      AUDIO   0      3728:15:16(16777141)     00:00:00(-16747844)
 2      AUDIO   0      06:30:47( 29297)     05:04:43( 22843)
 3      AUDIO   0      11:35:15( 52140)     04:46:42( 21492)
 4      AUDIO   0      16:21:57( 73632)     04:55:35( 22160)
 5      AUDIO   0      21:17:17( 95792)     01:23:55(  6280)
 6      AUDIO   0      22:40:72(102072)     04:09:48( 18723)
 7      AUDIO   0      26:50:45(120795)     03:59:32( 17957)
 8      AUDIO   0      30:50:02(138752)     05:11:38( 23363)
 9      AUDIO   0      36:01:40(162115)     07:27:37( 33562)
Leadout AUDIO   0      43:29:02(195677)
```

note how track 1 starts at 3728 minutes
