### ISSUE TITLE
Always fails to acquire metadata

### ISSUE THREAD

**Issue by zoqaeski** [whipper-team/whipper#551]
Whenever I rip a CD, whipper fails to acquire the metadata. The following error message is output (different MusicBrainz lookup URLs depending on the CD), and then the rip continues and labels every track as Unknown.
```
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr0
CDDB disc id: 860a8e0a
MusicBrainz disc id YxGRG_DKS9aFIKaAR1GoMEuwOuU-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+10+202867+150+6789+33515+60280+80657+102587+126266+145941+167293+194903&tracks=10&id=YxGRG_DKS9aFIKaAR1GoMEuwOuU-
Disc duration: 00:45:02.893, 10 audio tracks
WARNING:whipper.common.program:release not found: (NotFoundException(ResponseError()),)
WARNING:whipper.common.program:continuing without metadata
Submit this disc to MusicBrainz at the above URL.
```
The dependencies are installed, so I don't know how to debug why it isn't working.

**Comment by sfunk1x** [comment]
I'm also running into this fairly frequently. When ripping the CD, I see the `(NotFoundException(ResponseError()),)` error noted by @zoqaeski. When running the `mblookup` command on the release in question, I see the following:

```
sfunk1x@walkabout:~$ whipper mblookup 4a63e9ff-c7a3-4843-9027-fd161cc4d455
WARNING:whipper.command.main:Parameter 'use_https' is missing in versions of musicbrainzngs < 0.7. This means whipper will only be able to communicate with the configured MusicBrainz server ('musicbrainz.org') over plain HTTP. If a custom server which speaks HTTPS only has been declared, a suitable version of the musicbrainzngs module will be needed to make it work in whipper.
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:release-group>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:recording>, uncaught <first-release-date>
INFO:musicbrainzngs:in <ws2:work>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:work>, uncaught <language-list>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <work>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:recording>, uncaught <first-release-date>
INFO:musicbrainzngs:in <ws2:work>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:work>, uncaught <language-list>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <work>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:recording>, uncaught <first-release-date>
INFO:musicbrainzngs:in <ws2:work>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:work>, uncaught <language-list>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <work>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:recording>, uncaught <first-release-date>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:recording>, uncaught <first-release-date>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <work>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:recording>, uncaught <first-release-date>
INFO:musicbrainzngs:in <ws2:work>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:work>, uncaught <language-list>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <work>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:recording>, uncaught <first-release-date>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:work>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:work>, uncaught <language-list>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <work>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:recording>, uncaught <first-release-date>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:work>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:work>, uncaught <language-list>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:work>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <work>
INFO:musicbrainzngs:in <ws2:work>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <work>
INFO:musicbrainzngs:in <ws2:work>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ordering-key>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <work>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <work>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:recording>, uncaught <first-release-date>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:recording>, uncaught <first-release-date>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target-credit>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target-credit>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:work>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:work>, uncaught <language-list>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <work>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:recording>, uncaught <first-release-date>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:work>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:work>, uncaught <language-list>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:artist>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <artist>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <target>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <direction>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <begin>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <end>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <ended>
INFO:musicbrainzngs:in <ws2:relation>, uncaught <work>
    Artist: b'Diamond Head'
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.10.0', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.10.0-py3.7-linux-x86_64.egg/whipper/command/main.py", line 56, in main
    ret = cmd.do()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.10.0-py3.7-linux-x86_64.egg/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.10.0-py3.7-linux-x86_64.egg/whipper/command/mblookup.py", line 64, in do
    self._printMetadata(md)
  File "/usr/local/lib/python3.7/dist-packages/whipper-0.10.0-py3.7-linux-x86_64.egg/whipper/command/mblookup.py", line 29, in _printMetadata
    print('    Title:  %s' % md.releaseTitle.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by sfunk1x** [comment]
To follow up, I was able to find a musicbrainz entry that does actually work. Executing `whipper mblookup fed37cfc-2a6d-4569-9ac0-501a7c7598eb` results in a track listing of the entry as expected.

**Comment by sfunk1x** [comment]
Additional followup: this was tested with the docker image as well as latest code built locally.
