### ISSUE TITLE
whipper cd rip Fails with OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by Fregf** [whipper-team/whipper#565]
```
ERROR:asyncio:Exception in callback SyncRunner.schedule.<locals>.c() at /usr/local/lib/python3.10/dist-packages/whipper-0.10.1.dev23+g6ad681a-py3.10-linux-x86_64.egg/whipper/extern/task/task.py:520
handle: <TimerHandle when=15638.21351677 SyncRunner.schedule.<locals>.c() at /usr/local/lib/python3.10/dist-packages/whipper-0.10.1.dev23+g6ad681a-py3.10-linux-x86_64.egg/whipper/extern/task/task.py:520>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/whipper-0.10.1.dev23+g6ad681a-py3.10-linux-x86_64.egg/whipper/extern/task/task.py", line 522, in c
    callable_task(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/whipper-0.10.1.dev23+g6ad681a-py3.10-linux-x86_64.egg/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/usr/local/lib/python3.10/dist-packages/whipper-0.10.1.dev23+g6ad681a-py3.10-linux-x86_64.egg/whipper/program/cdrdao.py", line 159, in _done
    os.makedirs(t_dirn)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '/tmp/muziek/album/Jean‐Baptiste Lully; Les Talens Lyriques, Christophe Rousset, Eve-Maud Hubeaux, Cyril Auvity, Edwin Crossley-Mercer, Philippe Estèphe, Ambroisine Bré, Benedicte Tauran, Fabien Hyon, Aimery Lefèvre, Chœur de Chambre de Namur - Isis (Disc 1 of 2): Prologue'
CRITICAL:whipper.command.main:exception OSError at /usr/lib/python3.10/os.py:225: makedirs(): [Errno 36] File name too long: '/tmp/muziek/album/Jean‐Baptiste Lully; Les Talens Lyriques, Christophe Rousset, Eve-Maud Hubeaux, Cyril Auvity, Edwin Crossley-Mercer, Philippe Estèphe, Ambroisine Bré, Benedicte Tauran, Fabien Hyon, Aimery Lefèvre, Chœur de Chambre de Namur - Isis (Disc 1 of 2): Prologue'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/whipper-0.10.1.dev23+g6ad681a-py3.10-linux-x86_64.egg/whipper/extern/task/task.py", line 522, in c
    callable_task(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/whipper-0.10.1.dev23+g6ad681a-py3.10-linux-x86_64.egg/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/usr/local/lib/python3.10/dist-packages/whipper-0.10.1.dev23+g6ad681a-py3.10-linux-x86_64.egg/whipper/program/cdrdao.py", line 159, in _done
    os.makedirs(t_dirn)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '/tmp/muziek/album/Jean‐Baptiste Lully; Les Talens Lyriques, Christophe Rousset, Eve-Maud Hubeaux, Cyril Auvity, Edwin Crossley-Mercer, Philippe Estèphe, Ambroisine Bré, Benedicte Tauran, Fabien Hyon, Aimery Lefèvre, Chœur de Chambre de Namur - Isis (Disc 1 of 2): Prologue'
```

**Comment by dseomn** [comment]
Is this a duplicate of #453?
