### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by castilma** [whipper-team/whipper#592]
Hi, 

I'm trying to use whipper 0.10.0 and got this error
```
$ WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=/tmp/whipper.log whipper offset find
Track 1 finished, found 597 Q sub-channels with CRC errors
Track 2 finished, found 239 Q sub-channels with CRC errors
Track 3 finished, found 60 Q sub-channels with CRC errors
Track 4 finished, found 218 Q sub-channels with CRC errors
Track 5 finished, found 230 Q sub-channels with CRC errors
Track 6 finished, found 85 Q sub-channels with CRC errors
Track 7 finished, found 22 Q sub-channels with CRC errors
Track 8 finished, found 82 Q sub-channels with CRC errors
Track 9 finished, found 271 Q sub-channels with CRC errors
Track 10 finished, found 239 Q sub-channels with CRC errors
Track 11 finished, found 29 Q sub-channels with CRC errors
Track 12 finished, found 83 Q sub-channels with CRC errors
Track 13 finished, found 57 Q sub-channels with CRC errors
Track 14 finished, found 172 Q sub-channels with CRC errors
Track 15 finished, found 143 Q sub-channels with CRC errors
Track 16 finished, found 152 Q sub-channels with CRC errors
Track 17 finished, found 454 Q sub-channels with CRC errors
Track 18 finished, found 466 Q sub-channels with CRC errors
Track 19 finished, found 265 Q sub-channels with CRC errors
Track 20 finished, found 437 Q sub-channels with CRC errors
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/usr/lib/python3.10/site-packages/whipper/program/cdrdao.py", line 153, in _done
    self.toc.parse()
  File "/usr/lib/python3.10/site-packages/whipper/image/toc.py", line 203, in parse
    content = f.readlines()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 141: invalid start byte
```

The cd is cd 1 of ["the hitsound of motown"](https://musicbrainz.org/release/8755d40f-972a-4005-921a-934e863da58b).

[whipper.log.gz](https://github.com/whipper-team/whipper/files/11200038/whipper.log.gz)

**Comment by castilma** [comment]
This might be problem #591 since I'm on artix and have `cdrdao 1.2.5-1` installed. Unfortunately I don't have the earlier version cached under /var/cache/pacman/pkg so I cannot downgrade.

**Comment by rndmc12** [comment]
You can obtain old packages releases via the archive.ArchLinux. org server, btw.
