### ISSUE TITLE
`FileNotFoundError` when using `whipper cd rip`

### ISSUE THREAD

**Issue by SpecialBomb** [whipper-team/whipper#594]
This applies to whipper version `0.10.0` within a Void Linux environment. Whipper was obtained from the official Void package repository.

when using `whipper cd rip`, I appear to get an error regarding not being able to find a runtime directory that whipper generates in `/tmp`. I don't know what might be causing this. Here is an example of the output generated by the error:

```
[quen@slim:/tmp]$ whipper cd rip
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr0
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/usr/lib/python3.11/site-packages/whipper/program/cdrdao.py", line 153, in _done
    self.toc.parse()
  File "/usr/lib/python3.11/site-packages/whipper/image/toc.py", line 202, in parse
    with open(self._path) as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpuk9r8ic8.cdrdao.read-toc.whipper.task'
CRITICAL:whipper.command.main:exception FileNotFoundError at /usr/lib/python3.11/site-packages/whipper/image/toc.py:202: parse(): [Errno 2] No such file or directory: '/tmp/tmpuk9r8ic8.cdrdao.read-toc.whipper.task'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/usr/lib/python3.11/site-packages/whipper/program/cdrdao.py", line 153, in _done
    self.toc.parse()
  File "/usr/lib/python3.11/site-packages/whipper/image/toc.py", line 202, in parse
    with open(self._path) as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpuk9r8ic8.cdrdao.read-toc.whipper.task'
```

Absolutely no clue why this is happening. I thought maybe for some reason my `/tmp/` directory had restricted permissions, but they are completely normal. What could be going on here?

**Comment by Thra11** [comment]
I got the same error running whipper on NixOS. Downgrading cdrdao from 1.2.5 to 1.2.4 fixed the issue for me, so this may be a subtle variation on https://github.com/whipper-team/whipper/issues/591.

**Comment by SpecialBomb** [comment]
> I got the same error running whipper on NixOS. Downgrading cdrdao from 1.2.5 to 1.2.4 fixed the issue for me, so this may be a subtle variation on #591.

I will give this a shot and see what it results in for me, thanks for pointing me in the right direction for the time being. I suppose someone should probably get in contact with the cdrdao maintainers.

**Comment by AdamWill** [comment]
Yeah, I think @Thra11 is right here. I ran into this on Fedora 38 (just upgraded my only system with an optical disc drive from 37 to 38...) and applying https://github.com/cdrdao/cdrdao/pull/21 to cdrdao does seem to fix it. So I think we can call this effectively the same as 591, caused by cdrdao.

**Comment by BBaoVanC** [comment]
I'm encountering this issue even with Arch's patched 1.2.5-3 (and 1.2.5-2), but I didn't before. Not sure what has changed, the 1.2.5-3 rebuild from a couple days ago didn't change any of the actual contents of the package and was just regenerating a missing metadata file.

Even with discs that worked before, I have the issue. Any ideas?

<details>
<summary>My log</summary>

```
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr0
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/usr/lib/python3.12/site-packages/whipper/program/cdrdao.py", line 153, in _done
    self.toc.parse()
  File "/usr/lib/python3.12/site-packages/whipper/image/toc.py", line 202, in parse
    with open(self._path) as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmphuf8xnfj.cdrdao.read-toc.whipper.task'
CRITICAL:whipper.command.main:exception FileNotFoundError at /usr/lib/python3.12/site-packages/whipper/image/toc.py:202: parse(): [Errno 2] No such file or directory: '/tmp/tmphuf8xnfj.cdrdao.read-toc.whipper.task'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/whipper/program/cdrdao.py", line 115, in _read
    self._done()
  File "/usr/lib/python3.12/site-packages/whipper/program/cdrdao.py", line 153, in _done
    self.toc.parse()
  File "/usr/lib/python3.12/site-packages/whipper/image/toc.py", line 202, in parse
    with open(self._path) as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmphuf8xnfj.cdrdao.read-toc.whipper.task'
```

</details>

**Comment by BBaoVanC** [comment]
Nevermind, it turns out my drive numbering inexplicably changed. For some reason I get the FileNotFoundError mentioned instead of a message saying there's no CD in the drive. The drive giving me this issue is a TSSTcorp CDDVDW SH-222BB, although the drive seems to be dying because it won't read DVDs anymore and makes metallic noises with CDs (in other words, this may not be a software fault).

**Comment by dseomn** [comment]
From a glance at https://github.com/whipper-team/whipper/blob/develop/whipper/program/cdrdao.py it looks like the code is polling `Popen`, but isn't checking the [`returncode`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.returncode) attribute after the `cdrdao` process exits. In my case below, it looks like there's either a bug in cdrdao or something weird about the CD itself.

Could whipper check cdrdao's exit code, and display the output if it's non-zero? That would have saved me some debugging trying to figure out why a file didn't exist, when the real issue was that cdrdao failed.

```
$ cdrdao read-toc --fast-toc --device /dev/sr0 /tmp/tmp.9YdmdCkqbu/toc
/dev/sr0: HL-DT-ST BD-RE  WH16NS40      Rev: 1.05
CD-TEXT writing is supported.
Using driver: Generic SCSI-3/MMC - Version 2.0 (options 0x0010)

Reading toc data...

Track   Mode    Flags  Start                Length
------------------------------------------------------------
 1      AUDIO   2      00:00:00(     0)     02:32:09( 11409)
 2      AUDIO   2      02:32:09( 11409)     04:49:08( 21683)
 3      AUDIO   2      07:21:17( 33092)     06:01:42( 27117)
 4      AUDIO   2      13:22:59( 60209)     04:50:09( 21759)
 5      AUDIO   2      18:12:68( 81968)     01:52:15(  8415)
 6      AUDIO   2      20:05:08( 90383)     04:53:47( 22022)
 7      AUDIO   2      24:58:55(112405)     03:46:69( 17019)
 8      AUDIO   2      28:45:49(129424)     04:33:24( 20499)
 9      AUDIO   2      33:18:73(149923)     03:49:37( 17212)
10      AUDIO   2      37:08:35(167135)     04:14:26( 19076)
11      AUDIO   2      41:22:61(186211)     05:57:56( 26831)
12      AUDIO   2      47:20:42(213042)     06:08:02( 27602)
13      AUDIO   2      53:28:44(240644)     03:59:54( 17979)
14      AUDIO   2      57:28:23(258623)     04:25:22( 19897)
15      AUDIO   2      61:53:45(278520)     05:50:16( 26266)
Leadout AUDIO   0      67:43:61(304786)

PQ sub-channel reading (audio track) is supported, data format is BCD.
Raw P-W sub-channel reading (audio track) is supported.
Cooked R-W sub-channel reading (audio track) is supported.
Analyzing track 01 (AUDIO): start 00:00:00, length 02:32:09...
Analyzing track 02 (AUDIO): start 02:32:09, length 04:49:08...
Analyzing track 03 (AUDIO): start 07:21:17, length 06:01:42...
Analyzing track 04 (AUDIO): start 13:22:59, length 04:50:09...
Analyzing track 05 (AUDIO): start 18:12:68, length 01:52:15...
Analyzing track 06 (AUDIO): start 20:05:08, length 04:53:47...
Analyzing track 07 (AUDIO): start 24:58:55, length 03:46:69...
Analyzing track 08 (AUDIO): start 28:45:49, length 04:33:24...
Analyzing track 09 (AUDIO): start 33:18:73, length 03:49:37...
Analyzing track 10 (AUDIO): start 37:08:35, length 04:14:26...
Analyzing track 11 (AUDIO): start 41:22:61, length 05:57:56...
Analyzing track 12 (AUDIO): start 47:20:42, length 06:08:02...
Analyzing track 13 (AUDIO): start 53:28:44, length 03:59:54...
Analyzing track 14 (AUDIO): start 57:28:23, length 04:25:22...
Analyzing track 15 (AUDIO): start 61:53:45, length 05:50:16...
Found CD-TEXT data.
INTERNAL ERROR: addCdTextItem: Track 16 is not available.
INTERNAL ERROR: addCdTextItem: Track 24 is not available.
INTERNAL ERROR: addCdTextItem: Track 28 is not available.
INTERNAL ERROR: addCdTextItem: Track 36 is not available.
INTERNAL ERROR: addCdTextItem: Track 40 is not available.
INTERNAL ERROR: addCdTextItem: Track 48 is not available.
INTERNAL ERROR: addCdTextItem: Track 52 is not available.
INTERNAL ERROR: addCdTextItem: Track 60 is not available.
INTERNAL ERROR: addCdTextItem: Track 64 is not available.
INTERNAL ERROR: addCdTextItem: Track 72 is not available.
INTERNAL ERROR: addCdTextItem: Track 76 is not available.
INTERNAL ERROR: addCdTextItem: Track 84 is not available.
INTERNAL ERROR: addCdTextItem: Track 96 is not available.
cdrdao: Toc.cc:898: void Toc::addCdTextItem(int, CdTextItem*): Assertion `trackNr >= 0 && trackNr <= 99' failed.
Aborted                    cdrdao read-toc --fast-toc --device /dev/sr0 /tmp/tmp.9YdmdCkqbu/toc
$ echo $?
134
```

Edit: I filed https://github.com/cdrdao/cdrdao/issues/80 for the assertion failure in cdrdao.
