### ISSUE TITLE
unsupported operand type(s) for /: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by mitcoding** [whipper-team/whipper#601]
Code needs boundary checking to make sure NoneType is not Mathematically manipulated otherwise the program quits due to invalid type casting. This particular issue was discovered when my SOX stopped working so the /common/encode.py was setting result.peak = None. Thus the error in the issue's title was getting thrown as soon as /command/cd.py called print('Peak level: %.6f' % (trackResult.peak / 32768.0)) after the first tracked was ripped successfully and encoded to flac.

WARNING:whipper.program.sox:SoX peak detection failed: 127
INFO:whipper.program.cdparanoia:checksums match, 30e311eb
INFO:whipper.command.cd:CRCs match for track 1
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.10.0', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python3.8/dist-packages/whipper-0.10.0-py3.8-linux-x86_64.egg/whipper/command/main.py", line 56, in main
    ret = cmd.do()
  File "/usr/local/lib/python3.8/dist-packages/whipper-0.10.0-py3.8-linux-x86_64.egg/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.8/dist-packages/whipper-0.10.0-py3.8-linux-x86_64.egg/whipper/command/basecommand.py", line 141, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.8/dist-packages/whipper-0.10.0-py3.8-linux-x86_64.egg/whipper/command/cd.py", line 203, in do
    ret = self.doCommand()
  File "/usr/local/lib/python3.8/dist-packages/whipper-0.10.0-py3.8-linux-x86_64.egg/whipper/command/cd.py", line 559, in doCommand
    _ripIfNotRipped(i + 1)
  File "/usr/local/lib/python3.8/dist-packages/whipper-0.10.0-py3.8-linux-x86_64.egg/whipper/command/cd.py", line 519, in _ripIfNotRipped
    print('Peak level: %.6f' % (trackResult.peak / 32768.0))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

**Comment by TJFOE** [comment]
I get the same error at the end. And two files:

00_Hidden Track One Audio.flac
Clannad_Legend.toc

Attached two files with the Logs and the commands with output. I hope it is ok, to send this inside this issue...
[whipper.log.gz](https://github.com/whipper-team/whipper/files/15428563/whipper.log.gz)
[whipper_debug_and_rip.txt](https://github.com/whipper-team/whipper/files/15428566/whipper_debug_and_rip.txt)
