### ISSUE TITLE
`drive analyze` raised `TypeError: sequence item 0: expected str instance, bytes found`

### ISSUE THREAD

**Issue by FredGandt** [whipper-team/whipper#608]
- Installed via cmd `apt install whipper` on Linux Mint 21.3 Virginia
- Inserted disc 1 of legit [release of Goldie's Timeless](https://musicbrainz.org/release/81252b64-2b54-3f36-b9cf-756d7fd22bc4) into my ATAPI - iHAS124 drive
  - Only optical drive
  - Known to work well with other rippers incl. EAC, Sound Juicer and Asunder
- Entered cmd `whipper drive analyze`
  - Witnessed drive being driven
  - Message in CLI: `Analyzing drive caching behaviour   0 %`
- Error message appeared in CLI:
```CRITICAL:whipper.command.main:exception TypeError at /usr/lib/python3/dist-packages/whipper/program/cdparanoia.py:606: failed(): sequence item 0: expected str instance, bytes found
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/whipper/common/task.py", line 89, in _read
    self._done()
  File "/usr/lib/python3/dist-packages/whipper/common/task.py", line 107, in _done
    self.failed()
  File "/usr/lib/python3/dist-packages/whipper/program/cdparanoia.py", line 606, in failed
    output = "".join(self._output)
TypeError: sequence item 0: expected str instance, bytes found
```
- Drive span down gradually

Tried again; this series of events happened twice before preparing to submit this issue as follows:
- Entered `WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper drive analyze`
- Entered `gzip whipper.log`
- See attached: [whipper.log.gz](https://github.com/whipper-team/whipper/files/14473509/whipper.log.gz)

While writing this report, ran `whipper drive analyze` again to check if the percentage in `Analyzing drive caching behaviour   0 %` ever changed (I don't think so), but to my surprise, this last time got the following messages in the CLI:
```
INFO:whipper.command.drive:cdparanoia can defeat the audio cache on this drive
INFO:whipper.command.drive:adding drive cache behaviour to configuration file
```

**Comment by Ahrimdon** [comment]
Got the same error until I specified the drive. The usage examples being like they currently are is the real issue here xD. Should do --help or --full-help.

This command worked `whipper drive analyze -d /dev/sr1`
